init 3 python:
    mirageresearch4 = Book("notebook")
    mirageresearch4.Add_Page([
        "{b}Clues:{/b}",
        "",
        "Wingtips touching people's heads",
        "",
        "Rushes of wind??? Not DE",
        "",
        "Invisible 'walls'",
        "Mostly reported around Psychic class?",
        "Weird behavior of class in general may explain",
        "Above line may be hate speech, ignore",
        "",
        "Can turn invisible, probably--defense mechanism?",
        "{s}Regional variant flying Kecleon?{/s} No, that's dumb",
        "Look into anyway"], include_para_tab=False)
    mirageresearch4.Add_Page([
        "{b}Theories{/b}:",
        "",
        "Bird, most likely flying-type",
        "Look into non-flying birds ??",
        "{s}Torchic/Spritzee/Piplup?{/s} Obviously not them",
        "Still needs to fly",
        "",
        "Invisibility, aforementioned Psychic-type class happening, {s}whose residents I should mention I{/s}",
        "{s}wholly respect and appreciate, I swear I'm not a{/s}",
        "{s}bigot, if anything I'm jealous{/s}",
        "Probably Psychic-type",
        "Also possibly Ghost, lot of overlap (Sabrina, Morty, etc.)",
        "",
        "Mythical, must be, no known Pokémon has all traits",
        "{s}Ask first_name to confirm?{/s}"], include_para_tab=False)
    mirageresearch4.Add_Page([
        "{b}Capture Plans:{/b}",
        "",
        "{s}lure it with fish{/s}",
        "cafeteria keeps running out, probably silly idea anyway",
        "",
        "{s}capture footage of it on camera{/s}", 
        "it's invisible, idiot",
        "",
        "{s}ask Esper for help tracking it{/s}", 
        "Can't stop thinking about if I committed a hate crime. Don't want to have mind read rn",
        "",
        "Ask Yellow for help",
        "She can sense Pokémon--maybe she knows where it is?"], include_para_tab=False)