init python:

    #MOVEDEX
    #movedex/      Name/Type/Category/Contest/PP/Power/Accuracy/Effect/Description
    #      0          1    2        3       4  5     6        7      8           9

    def GetMove(name):
        for num in range(0, len(movedex)):
            if (movedex[num][DexMacros.Name] == name):
                moveentry = movedex[num]
                return Move(moveentry[0], moveentry[1], moveentry[2], moveentry[3], moveentry[4], moveentry[5], moveentry[6], moveentry[7], moveentry[8], moveentry[9])
        return Move(999, "ERROR", "Bug", "Physical", "Clever", 20, 60, 5, -1, "This move should not show up. If it does, let me know.")

    def GetStartingMoves(pkmn):
        finalmoves = []
        newmoves = GetLevelMoves(pkmn, 5)
        for possiblemove in newmoves:
            moveobj = GetMove(possiblemove[1])
            movepower = moveobj.Power
            if (isinstance(movepower, str) or movepower <= 70):
                finalmoves.append(moveobj)
        finalmoves = finalmoves[-4:]

        return finalmoves

    def GetMovesForLevel(pkmn):
        finalmoves = []
        finalmovestrings = []
        newmoves = GetLevelMoves(pkmn, pkmn.GetLevel())[-4:]
        for possiblemove in newmoves:
            movename = possiblemove[1]
            if (movename not in finalmovestrings):
                moveobj = GetMove(movename)
                finalmoves.append(moveobj)
                finalmovestrings.append(movename)

        return finalmoves

define movedex =[[1,"Pound","Normal","Physical","Tough",35,40,1,0,"A damaging attack."],
    [2,"Karate Chop","Fighting","Physical","Tough",25,50,1,-1,"High critical hit ratio."],
    [3,"Double Slap","Normal","Physical","Cute",10,15,0.85,-1,"Hits 2-5 times in one turn."],
    [4,"Comet Punch","Normal","Physical","Tough",15,18,0.85,-1,"Hits 2-5 times in one turn."],
    [5,"Mega Punch","Normal","Physical","Tough",20,80,0.85,0,"A damaging attack."],
    [6,"Pay Day","Normal","Physical","Clever",20,40,1,-1,"Attacks by scattering coins everywhere. Your coins."],
    [7,"Fire Punch","Fire","Physical","Tough",15,75,1,-1,"May burn opponent."],
    [8,"Ice Punch","Ice","Physical","Beautiful",15,75,1,-1,"May freeze opponent."],
    [9,"Thunder Punch","Electric","Physical","Cool",15,75,1,-1,"May paralyze opponent."],
    [10,"Scratch","Normal","Physical","Tough",35,40,1,0,"A damaging attack."],
    [11,"Vise Grip","Normal","Physical","Tough",30,55,1,0,"A damaging attack."],
    [12,"Guillotine","Normal","Physical","Cool",5,0,"~",-1,"One-Hit-KO, if it hits."],
    [13,"Razor Wind","Normal","Special","Cool",10,80,1,-1,"Charges on first turn, attacks on second. High critical hit ratio."],
    [14,"Swords Dance","Normal","Status","Beautiful",20,0,"—",-1,"Sharply raises user's Attack."],
    [15,"Cut","Normal","Physical","Cool",30,50,0.95,0,"A damaging attack."],
    [16,"Gust","Flying","Special","Clever",35,40,1,-1,"Hits Pokémon using Fly/Bounce with double power."],
    [17,"Wing Attack","Flying","Physical","Cool",35,60,1,0,"A damaging attack."],
    [18,"Whirlwind","Normal","Status","Clever",20,0,1,-1,"In battles, the opponent switches. In the wild, the Pokémon runs."],
    [19,"Fly","Flying","Physical","Clever",15,90,0.95,-1,"Flies up on first turn, attacks on second turn."],
    [20,"Bind","Normal","Physical","Tough",20,15,.85,-1,"Traps opponent, damaging them for 4-5 turns."],
    [21,"Slam","Normal","Physical","Tough",20,80,0.75,0,"A damaging attack."],
    [22,"Vine Whip","Grass","Physical","Cool",25,45,1,0,"A damaging attack."],
    [23,"Stomp","Normal","Physical","Tough",20,65,1,-1,"May cause flinching. Double damage against Minimized opponents."],
    [24,"Double Kick","Fighting","Physical","Cool",30,30,1,-1,"Hits twice in one turn."],
    [25,"Mega Kick","Normal","Physical","Cool",5,120,0.75,0,"A damaging attack."],
    [26,"Jump Kick","Fighting","Physical","Cool",10,100,0.95,-1,"If it misses, the user loses half their HP."],
    [27,"Rolling Kick","Fighting","Physical","Cool",15,60,0.85,-1,"May cause flinching."],
    [28,"Sand Attack","Ground","Status","Cute",15,0,1,-1,"Lowers opponent's Accuracy."],
    [29,"Headbutt","Normal","Physical","Tough",15,70,1,-1,"May cause flinching."],
    [30,"Horn Attack","Normal","Physical","Cool",25,65,1,0,"A damaging attack."],
    [31,"Fury Attack","Normal","Physical","Cool",20,15,0.85,-1,"Hits 2-5 times in one turn."],
    [32,"Horn Drill","Normal","Physical","Cool",5,0,"~",-1,"One-Hit-KO, if it hits."],
    [33,"Tackle","Normal","Physical","Tough",35,40,1,0,"A damaging attack."],
    [34,"Body Slam","Normal","Physical","Tough",15,85,1,-1,"May paralyze opponent."],
    [35,"Wrap","Normal","Physical","Tough",20,15,.9,-1,"Traps opponent, damaging them for 4-5 turns."],
    [36,"Take Down","Normal","Physical","Tough",20,90,0.85,-1,"User receives recoil damage."],
    [37,"Thrash","Normal","Physical","Tough",10,120,1,4,"User attacks for 2-3 turns but then becomes confused."],
    [38,"Double-Edge","Normal","Physical","Tough",15,120,1,-1,"User receives recoil damage."],
    [39,"Tail Whip","Normal","Status","Cute",30,0,"-","","Lowers opponent's Defense."],
    [40,"Poison Sting","Poison","Physical","Clever",35,15,1,-1,"May poison the opponent."],
    [41,"Twineedle","Bug","Physical","Cool",20,25,1,-1,"Hits twice in one turn. May poison opponent."],
    [42,"Pin Missile","Bug","Physical","Cool",20,25,.95,-1,"Hits 2-5 times in one turn."],
    [43,"Leer","Normal","Status","Cool",30,0,1,-1,"Lowers opponent's Defense."],
    [44,"Bite","Dark","Physical","Tough",25,60,1,8,"May cause flinching."],
    [45,"Growl","Normal","Status","Cute",40,0,1,-1,"Lowers opponent's Attack."],
    [46,"Roar","Normal","Status","Cool",20,0,"—",-1,"In battles, the opponent switches. In the wild, the Pokémon runs."],
    [47,"Sing","Normal","Status","Cute",15,0,0.55,-1,"Puts opponent to sleep."],
    [48,"Supersonic","Normal","Status","Clever",20,0,0.55,-1,"Confuses opponent."],
    [49,"Sonic Boom","Normal","Special","Cool",20,0,0.9,-1,"Always inflicts 20 HP."],
    [50,"Disable","Normal","Status","Clever",20,0,1,-1,"Opponent can't use its last attack for a few turns."],
    [51,"Acid","Poison","Special","Clever",30,40,1,-1,"May lower opponent's Special Defense."],
    [52,"Ember","Fire","Special","Cute",25,40,1,-1,"May burn opponent."],
    [53,"Flamethrower","Fire","Special","Beautiful",15,90,1,-1,"May burn opponent."],
    [54,"Mist","Ice","Status","Beautiful",30,0,"—",-1,"User's stats cannot be changed for a period of time."],
    [55,"Water Gun","Water","Special","Cute",25,40,1,0,"A damaging attack."],
    [56,"Hydro Pump","Water","Special","Beautiful",5,110,0.8,0,"A damaging attack."],
    [57,"Surf","Water","Special","Beautiful",15,90,1,-1,"Hits all adjacent Pokémon."],
    [58,"Ice Beam","Ice","Special","Beautiful",10,90,1,-1,"May freeze opponent."],
    [59,"Blizzard","Ice","Special","Beautiful",5,110,.7,-1,"May freeze opponent."],
    [60,"Psybeam","Psychic","Special","Beautiful",20,65,1,-1,"May confuse opponent."],
    [61,"Bubble Beam","Water","Special","Beautiful",20,65,1,-1,"May lower opponent's Speed."],
    [62,"Aurora Beam","Ice","Special","Beautiful",20,65,1,-1,"May lower opponent's Attack."],
    [63,"Hyper Beam","Normal","Special","Cool",5,150,0.9,-1,"User must recharge next turn."],
    [64,"Peck","Flying","Physical","Cool",35,35,1,0,"A damaging attack."],
    [65,"Drill Peck","Flying","Physical","Cool",20,80,1,0,"A damaging attack."],
    [66,"Submission","Fighting","Physical","Cool",20,80,0.8,-1,"User receives recoil damage."],
    [67,"Low Kick","Fighting","Physical","Tough",20,0,1,-1,"The heavier the opponent, the stronger the attack."],
    [68,"Counter","Fighting","Physical","Tough",20,0,1,-1,"When hit by a Physical Attack, user strikes back with 2x power."],
    [69,"Seismic Toss","Fighting","Physical","Tough",20,0,1,-1,"Inflicts damage equal to user's level."],
    [70,"Strength","Normal","Physical","Tough",15,80,1,0,"A damaging attack."],
    [71,"Absorb","Grass","Special","Clever",15,20,1,"","User recovers half the HP inflicted on opponent."],
    [72,"Mega Drain","Grass","Special","Clever",15,40,1,-1,"User recovers half the HP inflicted on opponent."],
    [73,"Leech Seed","Grass","Status","Clever",10,0,0.9,-1,"Drains HP from opponent each turn."],
    [74,"Growth","Normal","Status","Beautiful",20,0,"—",-1,"Raises user's Attack and Special Attack."],
    [75,"Razor Leaf","Grass","Physical","Cool",25,55,0.95,-1,"High critical hit ratio."],
    [76,"Solar Beam","Grass","Special","Cool",10,200,1,-1,"Charges on first turn, attacks on second."],
    [77,"Poison Powder","Poison","Status","Clever",35,0,0.75,-1,"Poisons opponent."],
    [78,"Stun Spore","Grass","Status","Clever",30,0,0.75,-1,"Paralyzes opponent."],
    [79,"Sleep Powder","Grass","Status","Clever",15,0,0.75,-1,"Puts opponent to sleep."],
    [80,"Petal Dance","Grass","Special","Beautiful",10,120,1,4,"User attacks for 2-3 turns but then becomes confused."],
    [81,"String Shot","Bug","Status","Clever",40,0,0.95,-1,"Sharply lowers opponent's Speed."],
    [82,"Dragon Rage","Dragon","Special","Cool",10,0,1,-1,"Always inflicts 40 HP."],
    [83,"Fire Spin","Fire","Special","Beautiful",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."],
    [84,"Thunder Shock","Electric","Special","Cool",30,40,1,-1,"May paralyze opponent."],
    [85,"Thunderbolt","Electric","Special","Cool",15,90,1,-1,"May paralyze opponent."],
    [86,"Thunder Wave","Electric","Status","Cool",20,0,.9,-1,"Paralyzes opponent."],
    [87,"Thunder","Electric","Special","Cool",10,110,0.7,-1,"May paralyze opponent."],
    [88,"Rock Throw","Rock","Physical","Tough",15,50,.9,0,"A damaging attack."],
    [89,"Earthquake","Ground","Physical","Tough",10,100,1,0,"Power is doubled if opponent is underground from using Dig."],
    [90,"Fissure","Ground","Physical","Tough",5,0,"~",-1,"One-Hit-KO, if it hits."],
    [91,"Dig","Ground","Physical","Tough",10,80,1,-1,"Digs underground on first turn, attacks on second."],
    [92,"Toxic","Poison","Status","Clever",10,0,.90,-1,"Badly poisons opponent."],
    [93,"Confusion","Psychic","Special","Clever",25,50,1,-1,"May confuse opponent."],
    [94,"Psychic","Psychic","Special","Clever",10,90,1,-1,"May lower opponent's Special Defense."],
    [95,"Hypnosis","Psychic","Status","Clever",20,0,.6,-1,"Puts opponent to sleep."],
    [96,"Meditate","Psychic","Status","Beautiful",40,0,"—",5,"Raises user's Attack."],
    [97,"Agility","Psychic","Status","Cool",30,0,"—",-1,"Sharply raises user's Speed."],
    [98,"Quick Attack","Normal","Physical","Cool",30,40,1,-1,"User attacks first."],
    [99,"Rage","Normal","Physical","Tough",20,20,1,-1,"Raises user's Attack when hit."],
    [100,"Teleport","Psychic","Status","Cool",20,0,"—",-1,"Always allows user to switch out."],
    [101,"Night Shade","Ghost","Special","Clever",15,0,1,-1,"Inflicts damage equal to user's level."],
    [102,"Mimic","Normal","Status","Cute",10,0,"-",-1,"Copies the opponent's last move."],
    [103,"Screech","Normal","Status","Clever",40,0,0.85,-1,"Sharply lowers opponent's Defense."],
    [104,"Double Team","Normal","Status","Cool",15,0,"—",-1,"Raises user's Evasiveness."],
    [105,"Recover","Normal","Status","Clever",10,0,"—",-1,"User recovers half its max HP."],
    [106,"Harden","Normal","Status","Tough",30,0,"—",-1,"Raises user's Defense."],
    [107,"Minimize","Normal","Status","Cute",10,0,"—",-1,"Sharply raises user's Evasiveness."],
    [108,"Smokescreen","Normal","Status","Clever",20,0,1,-1,"Lowers opponent's Accuracy."],
    [109,"Confuse Ray","Ghost","Status","Clever",10,0,1,-1,"Confuses opponent."],
    [110,"Withdraw","Water","Status","Cute",40,0,"—",-1,"Raises user's Defense."],
    [111,"Defense Curl","Normal","Status","Cute",40,0,"—",-1,"Raises user's Defense."],
    [112,"Barrier","Psychic","Status","Cool",20,0,"—",-1,"Sharply raises user's Defense."],
    [113,"Light Screen","Psychic","Status","Beautiful",30,0,"—",-1,"Halves damage from Special attacks for 5 turns."],
    [114,"Haze","Ice","Status","Beautiful",30,0,"-",-1,"Resets all stat changes."],
    [115,"Reflect","Psychic","Status","Clever",20,0,"—",-1,"Halves damage from Physical attacks for 5 turns."],
    [116,"Focus Energy","Normal","Status","Cool",30,0,"—",-1,"Increases critical hit ratio."],
    [117,"Bide","Normal","Physical","Tough",10,0,"-",-1,"User takes damage for two turns then strikes back double."],
    [118,"Metronome","Normal","Status","Cute",10,0,"—",-1,"User performs almost any move in the game at random."],
    [119,"Mirror Move","Flying","Status","Clever",20,0,"—",-1,"User performs the opponent's last move."],
    [120,"Self-Destruct","Normal","Physical","Beautiful",5,200,1,-1,"User faints."],
    [121,"Egg Bomb","Normal","Physical","Cute",10,100,0.75,0,"A damaging attack."],
    [122,"Lick","Ghost","Physical","Cute",30,30,1,-1,"May paralyze opponent."],
    [123,"Smog","Poison","Special","Tough",20,30,0.7,-1,"May poison opponent."],
    [124,"Sludge","Poison","Special","Tough",20,65,1,-1,"May poison opponent."],
    [125,"Bone Club","Ground","Physical","Tough",20,65,0.85,-1,"May cause flinching."],
    [126,"Fire Blast","Fire","Special","Beautiful",5,110,0.85,-1,"May burn opponent."],
    [127,"Waterfall","Water","Physical","Tough",15,80,1,-1,"May cause flinching."],
    [128,"Clamp","Water","Physical","Tough",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."],
    [129,"Swift","Normal","Special","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [130,"Skull Bash","Normal","Physical","Tough",10,130,1,-1,"Raises Defense on first turn, attacks on second."],
    [131,"Spike Cannon","Normal","Physical","Cool",15,20,1,-1,"Hits 2-5 times in one turn."],
    [132,"Constrict","Normal","Physical","Tough",35,10,1,-1,"May lower opponent's Speed by one stage."],
    [133,"Amnesia","Psychic","Status","Cute",20,0,"—",-1,"Sharply raises user's Special Defense."],
    [134,"Kinesis","Psychic","Status","Clever",15,0,0.8,-1,"Lowers opponent's Accuracy."],
    [135,"Soft-Boiled","Normal","Status","Cute",10,0,"—",-1,"User recovers half its max HP."],
    [136,"High Jump Kick","Fighting","Physical","Cool",10,130,0.9,-1,"If it misses, the user loses half their HP."],
    [137,"Glare","Normal","Status","Tough",30,0,1,-1,"Paralyzes opponent."],
    [138,"Dream Eater","Psychic","Special","Clever",15,100,1,-1,"User recovers half the HP inflicted on a sleeping opponent."],
    [139,"Poison Gas","Poison","Status","Clever",40,0,.90,-1,"Poisons opponent."],
    [140,"Barrage","Normal","Physical","Cute",20,15,0.85,-1,"Hits 2-5 times in one turn."],
    [141,"Leech Life","Bug","Physical","Clever",10,80,1,-1,"User recovers half the HP inflicted on opponent."],
    [142,"Lovely Kiss","Normal","Status","Beautiful",10,0,0.75,-1,"Puts opponent to sleep."],
    [143,"Sky Attack","Flying","Physical","Cool",5,200,0.9,-1,"Charges on first turn, attacks on second. May cause flinching."],
    [144,"Transform","Normal","Status","Clever",10,0,"—",-1,"User takes on the form and attacks of the opponent."],
    [145,"Bubble","Water","Special","Cute",30,40,1,-1,"May lower opponent's Speed."],
    [146,"Dizzy Punch","Normal","Physical","Cute",10,70,1,-1,"May confuse opponent."],
    [147,"Spore","Grass","Status","Beautiful",15,0,1,-1,"Puts opponent to sleep."],
    [148,"Flash","Normal","Status","Beautiful",20,0,1,-1,"Lowers opponent's Accuracy."],
    [149,"Psywave","Psychic","Special","Clever",15,0,1,-1,"Inflicts random damage unaffected by weakness or resistance."],
    [150,"Splash","Normal","Status","Cute",40,0,"—","","Doesn't do ANYTHING."],
    [151,"Acid Armor","Poison","Status","Tough",20,0,"—",-1,"Sharply raises user's Defense."],
    [152,"Crabhammer","Water","Physical","Tough",10,100,.90,-1,"High critical hit ratio."],
    [153,"Explosion","Normal","Physical","Beautiful",5,250,1,-1,"User faints."],
    [154,"Fury Swipes","Normal","Physical","Tough",15,18,0.8,-1,"Hits 2-5 times in one turn."],
    [155,"Bonemerang","Ground","Physical","Tough",10,50,0.9,-1,"Hits twice in one turn."],
    [156,"Rest","Psychic","Status","Cute",10,0,"—",-1,"User sleeps for 2 turns, but user is fully healed."],
    [157,"Rock Slide","Rock","Physical","Tough",10,75,0.9,-1,"May cause flinching."],
    [158,"Hyper Fang","Normal","Physical","Cool",15,80,0.9,-1,"May cause flinching."],
    [159,"Sharpen","Normal","Status","Cute",30,0,"—",-1,"Raises user's Attack."],
    [160,"Conversion","Normal","Status","Beautiful",30,0,"—",-1,"Changes user's type to that of its first move."],
    [161,"Tri Attack","Normal","Special","Beautiful",10,80,1,-1,"May paralyze, burn or freeze opponent."],
    [162,"Super Fang","Normal","Physical","Tough",10,0,0.9,-1,"Always takes off half of the opponent's HP."],
    [163,"Slash","Normal","Physical","Cool",20,70,1,-1,"High critical hit ratio."],
    [164,"Substitute","Normal","Status","Cute",10,0,"—",-1,"Uses HP to creates a decoy that takes hits."],
    [165,"Struggle","Normal","Physical","Tough",99,50,"—",-1,"Only usable when all PP are gone. Hurts the user."],
    [166,"Sketch","Normal","Status","Clever",1,0,"—",-1,"Permanently copies the opponent's last move."],
    [167,"Triple Kick","Fighting","Physical","Cool",10,10,0.9,-1,"Hits thrice in one turn at increasing power."],
    [168,"Thief","Dark","Physical","Tough",25,60,1,-1,"Also steals opponent's held item."],
    [169,"Spider Web","Bug","Status","Clever",10,0,"—",-1,"Opponent cannot escape/switch."],
    [170,"Mind Reader","Normal","Status","Clever",5,0,"-",-1,"User's next attack is guaranteed to hit."],
    [171,"Nightmare","Ghost","Status","Clever",15,0,1,-1,"The sleeping opponent loses 25% of its max HP each turn."],
    [172,"Flame Wheel","Fire","Physical","Beautiful",25,60,1,-1,"May burn opponent."],
    [173,"Snore","Normal","Special","Cute",15,50,1,-1,"Can only be used if asleep. May cause flinching."],
    [174,"Curse","Ghost","Status","Tough",10,0,"—",-1,"Different effect for Ghosts."],
    [175,"Flail","Normal","Physical","Cute",15,0,1,-1,"The lower the user's HP, the higher the power."],
    [176,"Conversion 2","Normal","Status","Beautiful",30,0,"—",-1,"User changes type to become resistant to opponent's last move."],
    [177,"Aeroblast","Flying","Special","Cool",5,100,0.95,-1,"High critical hit ratio."],
    [178,"Cotton Spore","Grass","Status","Beautiful",40,0,1,-1,"Sharply lowers opponent's Speed."],
    [179,"Reversal","Fighting","Physical","Cool",15,0,1,-1,"The lower the user's HP, the higher the power."],
    [180,"Spite","Ghost","Status","Tough",10,0,1,-1,"The opponent's last move loses 2-5 PP."],
    [181,"Powder Snow","Ice","Special","Beautiful",25,40,1,-1,"May freeze opponent."],
    [182,"Protect","Normal","Status","Cute",10,0,"—",-1,"Protects the user, but may fail if used consecutively."],
    [183,"Mach Punch","Fighting","Physical","Cool",30,40,1,-1,"User attacks first."],
    [184,"Scary Face","Normal","Status","Tough",10,0,1,-1,"Sharply lowers opponent's Speed."],
    [185,"Feint Attack","Dark","Physical","Clever",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [186,"Sweet Kiss","Fairy","Status","Cute",10,0,0.75,-1,"Confuses opponent."],
    [187,"Belly Drum","Normal","Status","Cute",10,0,"—",-1,"User loses 50% of its max HP, but Attack raises to maximum."],
    [188,"Sludge Bomb","Poison","Special","Tough",10,90,1,-1,"May poison opponent."],
    [189,"Mud-Slap","Ground","Special","Cute",10,20,1,-1,"Lowers opponent's Accuracy."],
    [190,"Octazooka","Water","Special","Tough",10,65,0.85,-1,"May lower opponent's Accuracy."],
    [191,"Spikes","Ground","Status","Clever",20,0,"—",-1,"Hurts opponents when they switch into battle."],
    [192,"Zap Cannon","Electric","Special","Cool",5,120,0.5,-1,"Paralyzes opponent."],
    [193,"Foresight","Normal","Status","Clever",40,0,"—",-1,"Resets opponent's Evasiveness, removes Ghost's immunities."],
    [194,"Destiny Bond","Ghost","Status","Clever",5,0,"—",-1,"If the user faints, the opponent also faints."],
    [195,"Perish Song","Normal","Status","Beautiful",5,0,"—",-1,"Any Pokémon in play when this attack is used faints in 3 turns."],
    [196,"Icy Wind","Ice","Special","Beautiful",15,55,0.95,-1,"Lowers opponent's Speed."],
    [197,"Detect","Fighting","Status","Cool",5,0,"—",-1,"Protects the user, but may fail if used consecutively."],
    [198,"Bone Rush","Ground","Physical","Tough",10,25,.90,-1,"Hits 2-5 times in one turn."],
    [199,"Lock-On","Normal","Status","Clever",5,0,"-",-1,"User's next attack is guaranteed to hit."],
    [200,"Outrage","Dragon","Physical","Cool",10,120,1,4,"User attacks for 2-3 turns but then becomes confused."],
    [201,"Sandstorm","Rock","Status","Tough",10,0,"—",-1,"Creates a sandstorm for 5 turns."],
    [202,"Giga Drain","Grass","Special","Clever",10,75,1,-1,"User recovers half the HP inflicted on opponent."],
    [203,"Endure","Normal","Status","Tough",10,0,"—",-1,"Always left with at least 1 HP, but may fail if used consecutively."],
    [204,"Charm","Fairy","Status","Cute",20,0,1,-1,"Sharply lowers opponent's Attack."],
    [205,"Rollout","Rock","Physical","Cute",20,30,0.9,-1,"Doubles in power each turn for 5 turns."],
    [206,"False Swipe","Normal","Physical","Cool",40,40,1,-1,"Always leaves opponent with at least 1 HP."],
    [207,"Swagger","Normal","Status","Cute",15,0,.85,-1,"Opponent becomes confused, but its Attack is sharply raised."],
    [208,"Milk Drink","Normal","Status","Cute",10,0,"—",-1,"User recovers half its max HP."],
    [209,"Spark","Electric","Physical","Cool",20,65,1,-1,"May paralyze opponent."],
    [210,"Fury Cutter","Bug","Physical","Cool",20,40,0.95,-1,"Power increases each turn."],
    [211,"Steel Wing","Steel","Physical","Cool",25,70,0.9,-1,"May raise user's Defense."],
    [212,"Mean Look","Normal","Status","Beautiful",5,0,"—",-1,"Opponent cannot flee or switch."],
    [213,"Attract","Normal","Status","Cute",15,0,1,-1,"If opponent is the opposite gender, it's less likely to attack."],
    [214,"Sleep Talk","Normal","Status","Cute",10,0,"—",-1,"User performs one of its own moves while sleeping."],
    [215,"Heal Bell","Normal","Status","Beautiful",5,0,"—",-1,"Heals the user's party's status conditions."],
    [216,"Return","Normal","Physical","Cute",20,0,1,1,"Power increases with higher Friendship."],
    [217,"Present","Normal","Physical","Cute",15,0,0.9,-1,"Either deals damage or heals."],
    [218,"Frustration","Normal","Physical","Cute",20,0,1,-1,"Power decreases with higher Friendship."],
    [219,"Safeguard","Normal","Status","Beautiful",25,0,"—",-1,"The user's party is protected from status conditions."],
    [220,"Pain Split","Normal","Status","Clever",20,0,"-",-1,"The user's and opponent's HP becomes the average of both."],
    [221,"Sacred Fire","Fire","Physical","Beautiful",5,100,0.95,-1,"May burn opponent."],
    [222,"Magnitude","Ground","Physical","Tough",30,0,1,-1,"Hits with random power."],
    [223,"Dynamic Punch","Fighting","Physical","Cool",5,100,0.5,-1,"Confuses opponent."],
    [224,"Megahorn","Bug","Physical","Cool",10,120,0.85,0,"A damaging attack."],
    [225,"Dragon Breath","Dragon","Special","Cool",20,60,1,-1,"May paralyze opponent."],
    [226,"Baton Pass","Normal","Status","Cute",40,0,"—",-1,"User switches out and gives stat changes to the incoming Pokémon."],
    [227,"Encore","Normal","Status","Cute",5,0,1,-1,"Forces opponent to keep using its last move for 3 turns."],
    [228,"Pursuit","Dark","Physical","Clever",20,40,1,-1,"Double power if the opponent is switching out."],
    [229,"Rapid Spin","Normal","Physical","Cool",40,50,1,-1,"Removes effects of trap moves, and boosts speed."],
    [230,"Sweet Scent","Normal","Status","Cute",20,0,1,-1,"Lowers opponent's Evasiveness."],
    [231,"Iron Tail","Steel","Physical","Cool",15,100,0.75,-1,"May lower opponent's Defense."],
    [232,"Metal Claw","Steel","Physical","Cool",35,50,0.95,-1,"May raise user's Attack."],
    [233,"Vital Throw","Fighting","Physical","Cool",10,70,"—",-1,"User attacks last, but ignores Accuracy and Evasiveness."],
    [234,"Morning Sun","Normal","Status","Beautiful",5,0,"—",-1,"User recovers HP. Amount varies with the weather."],
    [235,"Synthesis","Grass","Status","Clever",5,0,"—",-1,"User recovers HP. Amount varies with the weather."],
    [236,"Moonlight","Fairy","Status","Beautiful",5,0,"—",-1,"User recovers HP. Amount varies with the weather."],
    [237,"Hidden Power","Normal","Special","Clever",15,60,1,-1,"Type depends on user."],
    [238,"Cross Chop","Fighting","Physical","Cool",5,100,0.8,-1,"High critical hit ratio."],
    [239,"Twister","Dragon","Special","Cool",20,40,1,-1,"May cause flinching. Hits Pokémon using Fly/Bounce with double power."],
    [240,"Rain Dance","Water","Status","Beautiful",5,0,"—",-1,"Makes it rain for 5 turns."],
    [241,"Sunny Day","Fire","Status","Beautiful",5,0,"—",-1,"Makes it sunny for 5 turns."],
    [242,"Crunch","Dark","Physical","Tough",15,80,1,-1,"May lower opponent's Defense."],
    [243,"Mirror Coat","Psychic","Special","Beautiful",20,0,1,-1,"When hit by a Special Attack, user strikes back with 2x power."],
    [244,"Psych Up","Normal","Status","Clever",10,0,"—",-1,"Copies the opponent's stat changes."],
    [245,"Extreme Speed","Normal","Physical","Cool",5,80,1,-1,"User attacks first."],
    [246,"Ancient Power","Rock","Special","Tough",5,60,1,-1,"May raise all user's stats at once."],
    [247,"Shadow Ball","Ghost","Special","Clever",15,80,1,-1,"May lower opponent's Special Defense."],
    [248,"Future Sight","Psychic","Special","Clever",10,120,1,-1,"Damage occurs 2 turns later."],
    [249,"Rock Smash","Fighting","Physical","Tough",15,40,1,-1,"May lower opponent's Defense."],
    [250,"Whirlpool","Water","Special","Beautiful",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."],
    [251,"Beat Up","Dark","Physical","Clever",10,0,1,-1,"Each Pokémon in your party attacks."],
    [252,"Fake Out","Normal","Physical","Cute",10,40,1,-1,"User attacks first, foe flinches. Only usable on first turn."],
    [253,"Uproar","Normal","Special","Cute",10,90,1,-1,"User attacks for 3 turns and prevents sleep."],
    [254,"Stockpile","Normal","Status","Tough",20,0,"—",-1,"Stores energy for use with Spit Up and Swallow."],
    [255,"Spit Up","Normal","Special","Tough",10,0,1,-1,"Power depends on how many times the user performed Stockpile."],
    [256,"Swallow","Normal","Status","Tough",10,0,"—",-1,"The more times the user has performed Stockpile, the more HP is recovered."],
    [257,"Heat Wave","Fire","Special","Beautiful",10,95,0.9,-1,"May burn opponent."],
    [258,"Hail","Ice","Status","Beautiful",10,0,"—",-1,"Non-Ice types are damaged for 5 turns."],
    [259,"Torment","Dark","Status","Tough",15,0,1,-1,"Opponent cannot use the same move in a row."],
    [260,"Flatter","Dark","Status","Clever",15,0,1,-1,"Confuses opponent, but raises its Special Attack by two stages."],
    [261,"Will-O-Wisp","Fire","Status","Beautiful",15,0,.85,-1,"Burns opponent."],
    [262,"Memento","Dark","Status","Tough",10,0,1,-1,"User faints, sharply lowers opponent's Attack and Special Attack."],
    [263,"Facade","Normal","Physical","Cute",20,70,1,-1,"Power doubles if user is burned, poisoned, or paralyzed."],
    [264,"Focus Punch","Fighting","Physical","Tough",20,150,1,-1,"If the user is hit before attacking, it flinches instead."],
    [265,"Smelling Salts","Normal","Physical","Tough",10,70,1,-1,"Power doubles if opponent is paralyzed, but cures it."],
    [266,"Follow Me","Normal","Status","Cute",20,0,"—",-1,"In Multi Battles, the user takes all the attacks."],
    [267,"Nature Power","Normal","Status","Beautiful",20,0,"—",-1,"Uses a certain move based on the current terrain."],
    [268,"Charge","Electric","Status","Clever",20,0,"—",-1,"Raises user's Special Defense and next Electric move's power increases."],
    [269,"Taunt","Dark","Status","Clever",20,0,1,-1,"Opponent can only use moves that attack."],
    [270,"Helping Hand","Normal","Status","Clever",20,0,"—",-1,"In Multi Battles, boosts the power of the partner's move."],
    [271,"Trick","Psychic","Status","Clever",10,0,1,-1,"Swaps held items with another Pokémon."],
    [272,"Role Play","Psychic","Status","Cute",10,0,"—",-1,"User copies the opponent's Ability."],
    [273,"Wish","Normal","Status","Cute",10,0,"—",-1,"The user recovers HP in the following turn."],
    [274,"Assist","Normal","Status","Cute",20,0,"—",-1,"User performs a move known by its allies at random."],
    [275,"Ingrain","Grass","Status","Clever",20,0,"—",-1,"User restores HP each turn. User cannot escape/switch."],
    [276,"Superpower","Fighting","Physical","Tough",5,120,1,-1,"Lowers user's Attack and Defense."],
    [277,"Magic Coat","Psychic","Status","Beautiful",15,0,"—",-1,"Reflects moves that cause status conditions back to the attacker."],
    [278,"Recycle","Normal","Status","Clever",10,0,"—",-1,"User's used hold item is restored."],
    [279,"Revenge","Fighting","Physical","Tough",10,60,1,-1,"Power increases if user was hit first."],
    [280,"Brick Break","Fighting","Physical","Cool",15,75,1,-1,"Breaks through Reflect and Light Screen barriers."],
    [281,"Yawn","Normal","Status","Cute",10,0,"—",-1,"Puts opponent to sleep in the next turn."],
    [282,"Knock Off","Dark","Physical","Clever",20,65,1,-1,"Removes opponent's held item for the rest of the battle."],
    [283,"Endeavor","Normal","Physical","Tough",5,0,1,-1,"Reduces opponent's HP to same as user's."],
    [284,"Eruption","Fire","Special","Beautiful",5,150,1,-1,"Stronger when the user's HP is higher."],
    [285,"Skill Swap","Psychic","Status","Clever",10,0,"—",-1,"The user swaps Abilities with the opponent."],
    [286,"Imprison","Psychic","Status","Clever",10,0,"—",-1,"Opponent is unable to use moves that the user also knows."],
    [287,"Refresh","Normal","Status","Cute",20,0,"—",-1,"Cures paralysis, poison, and burns."],
    [288,"Grudge","Ghost","Status","Tough",5,0,"—",-1,"If the users faints after using this move, the PP for the opponent's last move is depleted."],
    [289,"Snatch","Dark","Status","Clever",10,0,"—",-1,"Steals the effects of the opponent's next move."],
    [290,"Secret Power","Normal","Physical","Clever",20,70,1,-1,"Effects of the attack vary with the location."],
    [291,"Dive","Water","Physical","Beautiful",10,80,1,-1,"Dives underwater on first turn, attacks on second turn."],
    [292,"Arm Thrust","Fighting","Physical","Tough",20,15,1,-1,"Hits 2-5 times in one turn."],
    [293,"Camouflage","Normal","Status","Clever",20,0,"—",-1,"Changes user's type according to the location."],
    [294,"Tail Glow","Bug","Status","Beautiful",20,0,"—",-1,"Drastically raises user's Special Attack."],
    [295,"Luster Purge","Psychic","Special","Clever",5,70,1,-1,"May lower opponent's Special Defense."],
    [296,"Mist Ball","Psychic","Special","Clever",5,70,1,-1,"May lower opponent's Special Attack."],
    [297,"Feather Dance","Flying","Status","Beautiful",15,0,1,-1,"Sharply lowers opponent's Attack."],
    [298,"Teeter Dance","Normal","Status","Cute",20,0,1,-1,"Confuses all Pokémon."],
    [299,"Blaze Kick","Fire","Physical","Cool",10,85,0.9,-1,"High critical hit ratio. May burn opponent."],
    [300,"Mud Sport","Ground","Status","Cute",15,0,"—",-1,"Weakens the power of Electric-type moves."],
    [301,"Ice Ball","Ice","Physical","Beautiful",20,30,0.9,-1,"Doubles in power each turn for 5 turns."],
    [302,"Needle Arm","Grass","Physical","Clever",15,60,1,-1,"May cause flinching."],
    [303,"Slack Off","Normal","Status","Cute",10,0,"—",-1,"User recovers half its max HP."],
    [304,"Hyper Voice","Normal","Special","Cool",10,90,1,0,"A damaging attack."],
    [305,"Poison Fang","Poison","Physical","Clever",15,50,1,-1,"May badly poison opponent."],
    [306,"Crush Claw","Normal","Physical","Cool",10,75,0.95,-1,"May lower opponent's Defense."],
    [307,"Blast Burn","Fire","Special","Beautiful",5,150,0.9,-1,"User must recharge next turn."],
    [308,"Hydro Cannon","Water","Special","Beautiful",5,150,0.9,-1,"User must recharge next turn."],
    [309,"Meteor Mash","Steel","Physical","Cool",10,90,.90,-1,"May raise user's Attack."],
    [310,"Astonish","Ghost","Physical","Cute",15,30,1,-1,"May cause flinching."],
    [311,"Weather Ball","Normal","Special","Beautiful",10,50,1,-1,"Move's power and type changes with the weather."],
    [312,"Aromatherapy","Grass","Status","Clever",5,0,"—",-1,"Cures all status problems in your party."],
    [313,"Fake Tears","Dark","Status","Cute",20,0,1,-1,"Sharply lowers opponent's Special Defense."],
    [314,"Air Cutter","Flying","Special","Cool",25,60,0.95,-1,"High critical hit ratio."],
    [315,"Overheat","Fire","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."],
    [316,"Odor Sleuth","Normal","Status","Clever",40,0,"—",-1,"Resets opponent's Evasiveness, removes Ghost's immunities."],
    [317,"Rock Tomb","Rock","Physical","Clever",15,60,.95,6,"Lowers opponent's Speed."],
    [318,"Silver Wind","Bug","Special","Beautiful",5,60,1,-1,"May raise all stats of user at once."],
    [319,"Metal Sound","Steel","Status","Clever",40,0,0.85,-1,"Sharply lowers opponent's Special Defense."],
    [320,"Grass Whistle","Grass","Status","Clever",15,0,0.55,-1,"Puts opponent to sleep."],
    [321,"Tickle","Normal","Status","Cute",20,0,1,-1,"Lowers opponent's Attack and Defense."],
    [322,"Cosmic Power","Psychic","Status","Beautiful",20,0,"—",-1,"Raises user's Defense and Special Defense."],
    [323,"Water Spout","Water","Special","Beautiful",5,150,1,-1,"The higher the user's HP, the higher the damage caused."],
    [324,"Signal Beam","Bug","Special","Beautiful",15,75,1,-1,"May confuse opponent."],
    [325,"Shadow Punch","Ghost","Physical","Clever",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [326,"Extrasensory","Psychic","Special","Cool",20,80,1,-1,"May cause flinching."],
    [327,"Sky Uppercut","Fighting","Physical","Cool",15,85,0.9,-1,"Hits the opponent, even during Fly."],
    [328,"Sand Tomb","Ground","Physical","Clever",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."],
    [329,"Sheer Cold","Ice","Special","Beautiful",5,0,"~",-1,"One-Hit-KO, if it hits."],
    [330,"Muddy Water","Water","Special","Tough",10,90,0.85,-1,"May lower opponent's Accuracy."],
    [331,"Bullet Seed","Grass","Physical","Cool",30,25,1,-1,"Hits 2-5 times in one turn."],
    [332,"Aerial Ace","Flying","Physical","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [333,"Icicle Spear","Ice","Physical","Beautiful",30,25,1,-1,"Hits 2-5 times in one turn."],
    [334,"Iron Defense","Steel","Status","Tough",15,0,"—",-1,"Sharply raises user's Defense."],
    [335,"Block","Normal","Status","Cute",5,0,"—",-1,"Opponent cannot flee or switch."],
    [336,"Howl","Normal","Status","Cool",40,0,"—",5,"Raises user's Attack."],
    [337,"Dragon Claw","Dragon","Physical","Cool",15,80,1,0,"A damaging attack."],
    [338,"Frenzy Plant","Grass","Special","Cool",5,150,0.9,-1,"User must recharge next turn."],
    [339,"Bulk Up","Fighting","Status","Cool",20,0,"—",-1,"Raises user's Attack and Defense."],
    [340,"Bounce","Flying","Physical","Cute",5,85,0.85,-1,"Springs up on first turn, attacks on second. May paralyze opponent."],
    [341,"Mud Shot","Ground","Special","Tough",15,55,0.95,-1,"Lowers opponent's Speed."],
    [342,"Poison Tail","Poison","Physical","Clever",25,50,1,-1,"High critical hit ratio. May poison opponent."],
    [343,"Covet","Normal","Physical","Cute",25,60,1,-1,"Opponent's item is stolen by the user."],
    [344,"Volt Tackle","Electric","Physical","Cool",15,120,1,-1,"User receives recoil damage. May paralyze opponent."],
    [345,"Magical Leaf","Grass","Special","Beautiful",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [346,"Water Sport","Water","Status","Cute",15,0,"—",-1,"Weakens the power of Fire-type moves."],
    [347,"Calm Mind","Psychic","Status","Clever",20,0,"—",-1,"Raises user's Special Attack and Special Defense."],
    [348,"Leaf Blade","Grass","Physical","Cool",15,90,1,-1,"High critical hit ratio."],
    [349,"Dragon Dance","Dragon","Status","Cool",20,0,"—",3,"Raises user's Attack and Speed."],
    [350,"Rock Blast","Rock","Physical","Tough",10,25,.90,-1,"Hits 2-5 times in one turn."],
    [351,"Shock Wave","Electric","Special","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [352,"Water Pulse","Water","Special","Beautiful",20,60,1,-1,"May confuse opponent."],
    [353,"Doom Desire","Steel","Special","Beautiful",5,140,1,-1,"Damage occurs 2 turns later."],
    [354,"Psycho Boost","Psychic","Special","Clever",5,140,0.9,-1,"Sharply lowers user's Special Attack."],
    [355,"Roost","Flying","Status","Clever",10,0,"—",2,"User recovers half of its max HP and loses the Flying type temporarily."],
    [356,"Gravity","Psychic","Status","Clever",5,0,"—",-1,"Prevents moves like Fly and Bounce and the Ability Levitate for 5 turns."],
    [357,"Miracle Eye","Psychic","Status","Clever",40,0,"—",-1,"Resets opponent's Evasiveness, removes Dark's Psychic immunity."],
    [358,"Wake-Up Slap","Fighting","Physical","Tough",10,70,1,-1,"Power doubles if opponent is asleep, but wakes it up."],
    [359,"Hammer Arm","Fighting","Physical","Tough",10,100,0.9,-1,"Lowers user's Speed."],
    [360,"Gyro Ball","Steel","Physical","Cool",5,0,1,-1,"The slower the user, the stronger the attack."],
    [361,"Healing Wish","Psychic","Status","Beautiful",10,0,"—",-1,"The user faints and the next Pokémon released is fully healed."],
    [362,"Brine","Water","Special","Tough",10,65,1,-1,"Power doubles if opponent's HP is less than 50%."],
    [363,"Natural Gift","Normal","Physical","Clever",15,0,1,-1,"Power and type depend on the user's held berry."],
    [364,"Feint","Normal","Physical","Clever",10,30,1,-1,"Breaks through protecting moves."],
    [365,"Pluck","Flying","Physical","Cute",20,60,1,-1,"If the opponent is holding a berry, its effect is stolen by user."],
    [366,"Tailwind","Flying","Status","Cool",15,0,"—",-1,"Doubles Speed for 4 turns."],
    [367,"Acupressure","Normal","Status","Tough",30,0,"—",-1,"Sharply raises a random stat."],
    [368,"Metal Burst","Steel","Physical","Cool",10,0,1,-1,"Deals damage equal to 1.5x opponent's attack."],
    [369,"U-turn","Bug","Physical","Cute",20,70,1,-1,"User switches out immediately after attacking."],
    [370,"Close Combat","Fighting","Physical","Tough",5,120,1,-1,"Lowers user's Defense and Special Defense."],
    [371,"Payback","Dark","Physical","Tough",10,50,1,-1,"Power doubles if the user was attacked first."],
    [372,"Assurance","Dark","Physical","Clever",10,60,1,-1,"Power doubles if opponent already took damage in the same turn."],
    [373,"Embargo","Dark","Status","Clever",15,0,1,-1,"Opponent cannot use items."],
    [374,"Fling","Dark","Physical","Tough",10,0,1,-1,"Power varies depending on the held item. Held item is consumed upon use."],
    [375,"Psycho Shift","Psychic","Status","Clever",10,0,1,-1,"Gives the opponent the user's status condition, if it hits."],
    [376,"Trump Card","Normal","Special","Cool",5,0,"—",-1,"The lower the PP, the higher the power."],
    [377,"Heal Block","Psychic","Status","Clever",15,0,1,-1,"Prevents the opponent from restoring HP for 5 turns."],
    [378,"Wring Out","Normal","Special","Tough",5,0,1,-1,"The higher the opponent's HP, the higher the damage."],
    [379,"Power Trick","Psychic","Status","Clever",10,0,"—",-1,"User's own Attack and Defense switch."],
    [380,"Gastro Acid","Poison","Status","Tough",10,0,1,-1,"Cancels out the effect of the opponent's Ability."],
    [381,"Lucky Chant","Normal","Status","Cute",30,0,"—",-1,"Opponent cannot land critical hits for 5 turns."],
    [382,"Me First","Normal","Status","Clever",20,0,"—",-1,"User copies the opponent's attack with 1.5× power."],
    [383,"Copycat","Normal","Status","Cute",20,0,"—",-1,"Copies the last successful move."],
    [384,"Power Swap","Psychic","Status","Clever",10,0,"—",-1,"User and opponent swap Attack and Special Attack."],
    [385,"Guard Swap","Psychic","Status","Clever",10,0,"—",-1,"User and opponent swap Defense and Special Defense."],
    [386,"Punishment","Dark","Physical","Cool",5,0,1,-1,"Power increases when opponent's stats have been raised."],
    [387,"Last Resort","Normal","Physical","Cute",5,140,1,-1,"Can only be used after all other moves are used."],
    [388,"Worry Seed","Grass","Status","Clever",10,0,1,-1,"Changes the opponent's Ability to Insomnia."],
    [389,"Sucker Punch","Dark","Physical","Clever",5,70,1,-1,"User attacks first, but only works if opponent is readying an attack."],
    [390,"Toxic Spikes","Poison","Status","Clever",20,0,"—",-1,"Poisons opponents when they switch into battle."],
    [391,"Heart Swap","Psychic","Status","Clever",10,0,"—",-1,"Stat changes are swapped with the opponent."],
    [392,"Aqua Ring","Water","Status","Beautiful",20,0,"—",-1,"Restores a little HP each turn."],
    [393,"Magnet Rise","Electric","Status","Clever",10,0,"—",-1,"User becomes immune to Ground-type moves for 5 turns."],
    [394,"Flare Blitz","Fire","Physical","Cool",15,120,1,-1,"User receives recoil damage. May burn opponent."],
    [395,"Force Palm","Fighting","Physical","Cool",10,60,1,-1,"May paralyze opponent."],
    [396,"Aura Sphere","Fighting","Special","Beautiful",20,80,"—",-1,"Ignores Accuracy and Evasiveness."],
    [397,"Rock Polish","Rock","Status","Tough",20,0,"—",-1,"Sharply raises user's Speed."],
    [398,"Poison Jab","Poison","Physical","Tough",20,80,1,-1,"May poison the opponent."],
    [399,"Dark Pulse","Dark","Special","Cool",15,80,1,-1,"May cause flinching."],
    [400,"Night Slash","Dark","Physical","Cool",15,70,1,-1,"High critical hit ratio."],
    [401,"Aqua Tail","Water","Physical","Beautiful",10,90,0.9,0,"A damaging attack."],
    [402,"Seed Bomb","Grass","Physical","Tough",15,80,1,0,"A damaging attack."],
    [403,"Air Slash","Flying","Special","Cool",15,75,0.95,-1,"May cause flinching."],
    [404,"X-Scissor","Bug","Physical","Cool",15,80,1,0,"A damaging attack."],
    [405,"Bug Buzz","Bug","Special","Beautiful",10,90,1,-1,"May lower opponent's Special Defense."],
    [406,"Dragon Pulse","Dragon","Special","Beautiful",10,85,1,0,"A damaging attack."],
    [407,"Dragon Rush","Dragon","Physical","Tough",10,100,0.75,-1,"May cause flinching."],
    [408,"Power Gem","Rock","Special","Beautiful",20,80,1,0,"A damaging attack."],
    [409,"Drain Punch","Fighting","Physical","Tough",10,75,1,-1,"User recovers half the HP inflicted on opponent."],
    [410,"Vacuum Wave","Fighting","Special","Cool",30,40,1,-1,"User attacks first."],
    [411,"Focus Blast","Fighting","Special","Cool",5,120,0.7,-1,"May lower opponent's Special Defense."],
    [412,"Energy Ball","Grass","Special","Beautiful",10,90,1,-1,"May lower opponent's Special Defense."],
    [413,"Brave Bird","Flying","Physical","Cool",15,120,1,-1,"User receives recoil damage."],
    [414,"Earth Power","Ground","Special","Beautiful",10,90,1,-1,"May lower opponent's Special Defense."],
    [415,"Switcheroo","Dark","Status","Clever",10,0,1,-1,"Swaps held items with another Pokémon."],
    [416,"Giga Impact","Normal","Physical","Tough",5,150,0.9,-1,"User must recharge next turn."],
    [417,"Nasty Plot","Dark","Status","Clever",20,0,"—",-1,"Sharply raises user's Special Attack."],
    [418,"Bullet Punch","Steel","Physical","Tough",30,40,1,-1,"User attacks first."],
    [419,"Avalanche","Ice","Physical","Beautiful",10,60,1,-1,"Power doubles if user took damage first."],
    [420,"Ice Shard","Ice","Physical","Beautiful",30,40,1,-1,"User attacks first."],
    [421,"Shadow Claw","Ghost","Physical","Cool",15,70,1,-1,"High critical hit ratio."],
    [422,"Thunder Fang","Electric","Physical","Cool",15,65,0.95,-1,"May cause flinching and/or paralyze opponent."],
    [423,"Ice Fang","Ice","Physical","Cool",15,65,0.95,-1,"May cause flinching and/or freeze opponent."],
    [424,"Fire Fang","Fire","Physical","Cool",15,65,0.95,-1,"May cause flinching and/or burn opponent."],
    [425,"Shadow Sneak","Ghost","Physical","Clever",30,40,1,-1,"User attacks first."],
    [426,"Mud Bomb","Ground","Special","Cute",10,65,0.85,-1,"May lower opponent's Accuracy."],
    [427,"Psycho Cut","Psychic","Physical","Cool",20,70,1,-1,"High critical hit ratio."],
    [428,"Zen Headbutt","Psychic","Physical","Clever",15,80,0.9,-1,"May cause flinching."],
    [429,"Mirror Shot","Steel","Special","Beautiful",10,65,0.85,-1,"May lower opponent's Accuracy."],
    [430,"Flash Cannon","Steel","Special","Beautiful",10,80,1,-1,"May lower opponent's Special Defense."],
    [431,"Rock Climb","Normal","Physical","Tough",20,90,0.85,-1,"May confuse opponent."],
    [432,"Defog","Flying","Status","Cool",15,0,"—",-1,"Lowers opponent's Evasiveness and clears fog."],
    [433,"Trick Room","Psychic","Status","Clever",5,0,"—",-1,"Slower Pokémon move first in the turn for 5 turns."],
    [434,"Draco Meteor","Dragon","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."],
    [435,"Discharge","Electric","Special","Beautiful",15,80,1,-1,"May paralyze opponent."],
    [436,"Lava Plume","Fire","Special","Tough",15,80,1,-1,"May burn opponent."],
    [437,"Leaf Storm","Grass","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."],
    [438,"Power Whip","Grass","Physical","Tough",10,120,0.85,0,"A damaging attack."],
    [439,"Rock Wrecker","Rock","Physical","Tough",5,150,0.9,-1,"User must recharge next turn."],
    [440,"Cross Poison","Poison","Physical","Cool",20,70,1,-1,"High critical hit ratio. May poison opponent."],
    [441,"Gunk Shot","Poison","Physical","Tough",5,120,.80,-1,"May poison opponent."],
    [442,"Iron Head","Steel","Physical","Tough",15,80,1,-1,"May cause flinching."],
    [443,"Magnet Bomb","Steel","Physical","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."],
    [444,"Stone Edge","Rock","Physical","Tough",5,100,0.8,-1,"High critical hit ratio."],
    [445,"Captivate","Normal","Status","Cute",20,0,1,-1,"Sharply lowers opponent's Special Attack if opposite gender."],
    [446,"Stealth Rock","Rock","Status","Cool",20,0,"—",-1,"Damages opponent switching into battle."],
    [447,"Grass Knot","Grass","Special","Cute",20,0,1,-1,"The heavier the opponent, the stronger the attack."],
    [448,"Chatter","Flying","Special","Cute",20,65,1,-1,"Confuses opponent."],
    [449,"Judgment","Normal","Special","Beautiful",10,100,1,-1,"Type depends on the Arceus Plate being held."],
    [450,"Bug Bite","Bug","Physical","Cute",20,60,1,-1,"Receives the effect from the opponent's held berry."],
    [451,"Charge Beam","Electric","Special","Beautiful",10,50,0.9,-1,"May raise user's Special Attack."],
    [452,"Wood Hammer","Grass","Physical","Tough",15,120,1,-1,"User receives recoil damage."],
    [453,"Aqua Jet","Water","Physical","Cool",20,40,1,-1,"User attacks first."],
    [454,"Attack Order","Bug","Physical","Clever",15,90,1,-1,"High critical hit ratio."],
    [455,"Defend Order","Bug","Status","Clever",10,0,"—",-1,"Raises user's Defense and Special Defense."],
    [456,"Heal Order","Bug","Status","Clever",10,0,"—",-1,"User recovers half its max HP."],
    [457,"Head Smash","Rock","Physical","Tough",5,150,0.8,-1,"User receives recoil damage."],
    [458,"Double Hit","Normal","Physical","Cool",10,35,0.9,-1,"Hits twice in one turn."],
    [459,"Roar of Time","Dragon","Special","Beautiful",5,150,0.9,-1,"User must recharge next turn."],
    [460,"Spacial Rend","Dragon","Special","Beautiful",5,100,0.95,-1,"High critical hit ratio."],
    [461,"Lunar Dance","Psychic","Status","Beautiful",10,0,"—",-1,"The user faints but the next Pokémon released is fully healed."],
    [462,"Crush Grip","Normal","Physical","Tough",5,0,1,-1,"More powerful when opponent has higher HP."],
    [463,"Magma Storm","Fire","Special","Tough",5,100,.75,-1,"Traps opponent, damaging them for 4-5 turns."],
    [464,"Dark Void","Dark","Status","Clever",10,0,.50,-1,"Puts all adjacent opponents to sleep."],
    [465,"Seed Flare","Grass","Special","Beautiful",5,120,0.85,-1,"May lower opponent's Special Defense."],
    [466,"Ominous Wind","Ghost","Special","Beautiful",5,60,1,-1,"May raise all user's stats at once."],
    [467,"Shadow Force","Ghost","Physical","Cool",5,120,1,-1,"Disappears on first turn, attacks on second. Can strike through Protect/Detect."],
    [468,"Hone Claws","Dark","Status","Cute",15,0,"—",-1,"Raises user's Attack and Accuracy."],
    [469,"Wide Guard","Rock","Status","Tough",10,0,"—",-1,"Protects the user's team from multi-target attacks."],
    [470,"Guard Split","Psychic","Status","Clever",10,0,"—",-1,"Averages Defense and Special Defense with the target."],
    [471,"Power Split","Psychic","Status","Clever",10,0,"—",-1,"Averages Attack and Special Attack with the target."],
    [472,"Wonder Room","Psychic","Status","Clever",10,0,"—",-1,"Swaps every Pokémon's Defense and Special Defense for 5 turns."],
    [473,"Psyshock","Psychic","Special","Beautiful",10,80,1,-1,"Inflicts damage based on the target's Defense, not Special Defense."],
    [474,"Venoshock","Poison","Special","Beautiful",10,65,1,-1,"Inflicts double damage if the target is poisoned."],
    [475,"Autotomize","Steel","Status","Beautiful",15,0,"—",-1,"Reduces weight and sharply raises Speed."],
    [476,"Rage Powder","Bug","Status","Clever",20,0,"—",-1,"Forces attacks to hit user, not team-mates."],
    [477,"Telekinesis","Psychic","Status","Clever",15,0,"—",-1,"Ignores opponent's Evasiveness for three turns, add Ground immunity."],
    [478,"Magic Room","Psychic","Status","Clever",10,0,"—",-1,"Suppresses the effects of held items for five turns."],
    [479,"Smack Down","Rock","Physical","Tough",15,50,1,-1,"Makes Flying-type Pokémon vulnerable to Ground moves."],
    [480,"Storm Throw","Fighting","Physical","Cool",10,60,1,-1,"Always results in a critical hit."],
    [481,"Flame Burst","Fire","Special","Beautiful",15,70,1,-1,"May also injure nearby Pokémon."],
    [482,"Sludge Wave","Poison","Special","Tough",10,95,1,-1,"May poison opponent."],
    [483,"Quiver Dance","Bug","Status","Beautiful",20,0,"-",-1,"Raises user's Special Attack, Special Defense and Speed."],
    [484,"Heavy Slam","Steel","Physical","Tough",10,0,1,-1,"The heavier the user, the stronger the attack."],
    [485,"Synchronoise","Psychic","Special","Clever",10,120,1,-1,"Hits any Pokémon that shares a type with the user."],
    [486,"Electro Ball","Electric","Special","Cool",10,0,1,-1,"The faster the user, the stronger the attack."],
    [487,"Soak","Water","Status","Cute",20,0,1,-1,"Changes the target's type to water."],
    [488,"Flame Charge","Fire","Physical","Cool",20,50,1,-1,"Raises user's Speed."],
    [489,"Coil","Poison","Status","Tough",20,0,"—",-1,"Raises user's Attack, Defense and Accuracy."],
    [490,"Low Sweep","Fighting","Physical","Clever",20,65,1,-1,"Lowers opponent's Speed."],
    [491,"Acid Spray","Poison","Special","Beautiful",20,40,1,-1,"Sharply lowers opponent's Special Defense."],
    [492,"Foul Play","Dark","Physical","Clever",15,95,1,-1,"Uses the opponent's Attack stat."],
    [493,"Simple Beam","Normal","Status","Cute",15,0,1,-1,"Changes target's ability to Simple."],
    [494,"Entrainment","Normal","Status","Cute",15,0,1,-1,"Makes target's ability same as user's."],
    [495,"After You","Normal","Status","Cute",15,0,"—",-1,"Gives target priority in the next turn."],
    [496,"Round","Normal","Special","Beautiful",15,60,1,-1,"Power increases if teammates use it in the same turn."],
    [497,"Echoed Voice","Normal","Special","Beautiful",15,40,1,-1,"Power increases each turn."],
    [498,"Chip Away","Normal","Physical","Tough",20,70,1,-1,"Ignores opponent's stat changes."],
    [499,"Clear Smog","Poison","Special","Beautiful",15,50,"—",-1,"Removes all of the target's stat changes."],
    [500,"Stored Power","Psychic","Special","Clever",10,20,1,-1,"Power increases when user's stats have been raised."],
    [501,"Quick Guard","Fighting","Status","Cool",15,0,"—",-1,"Protects the user's team from high-priority moves."],
    [502,"Ally Switch","Psychic","Status","Clever",15,0,"—",-1,"User switches with opposite teammate."],
    [503,"Scald","Water","Special","Tough",15,80,1,-1,"May burn opponent."],
    [504,"Shell Smash","Normal","Status","Tough",15,0,"—",-1,"Sharply raises user's Attack, Special Attack and Speed but lowers Defense and Special Defense."],
    [505,"Heal Pulse","Psychic","Status","Beautiful",10,0,"—",-1,"Restores half the target's max HP."],
    [506,"Hex","Ghost","Special","Clever",10,65,1,-1,"Inflicts more damage if the target has a status condition."],
    [507,"Sky Drop","Flying","Physical","Tough",10,60,1,-1,"Takes opponent into the air on first turn, drops them on second turn."],
    [508,"Shift Gear","Steel","Status","Clever",10,0,"—",-1,"Raises user's Attack and sharply raises Speed."],
    [509,"Circle Throw","Fighting","Physical","Cool",10,60,0.9,-1,"In battles, the opponent switches. In the wild, the Pokémon runs."],
    [510,"Incinerate","Fire","Special","Tough",15,60,1,-1,"Destroys the target's held berry."],
    [511,"Quash","Dark","Status","Clever",15,0,1,-1,"Makes the target act last this turn."],
    [512,"Acrobatics","Flying","Physical","Cool",15,55,1,-1,"Stronger when the user does not have a held item."],
    [513,"Reflect Type","Normal","Status","Clever",15,0,"—",-1,"User becomes the target's type."],
    [514,"Retaliate","Normal","Physical","Cool",5,70,1,-1,"Inflicts double damage if a teammate fainted on the last turn."],
    [515,"Final Gambit","Fighting","Special","Tough",5,0,1,-1,"Inflicts damage equal to the user's remaining HP. User faints."],
    [516,"Bestow","Normal","Status","Cute",15,0,"—",-1,"Gives the user's held item to the target."],
    [517,"Inferno","Fire","Special","Beautiful",5,100,0.5,-1,"Burns opponent."],
    [518,"Water Pledge","Water","Special","Beautiful",10,80,1,-1,"Added effects appear if preceded by Fire Pledge or succeeded by Grass Pledge."],
    [519,"Fire Pledge","Fire","Special","Beautiful",10,80,1,-1,"Added effects appear if combined with Grass Pledge or Water Pledge."],
    [520,"Grass Pledge","Grass","Special","Beautiful",10,80,1,-1,"Added effects appear if preceded by Water Pledge or succeeded by Fire Pledge."],
    [521,"Volt Switch","Electric","Special","Cool",20,70,1,-1,"User must switch out after attacking."],
    [522,"Struggle Bug","Bug","Special","Cute",20, 50,1,-1,"Lowers opponent's Special Attack."],
    [523,"Bulldoze","Ground","Physical","Tough",20,60,1,-1,"Lowers opponent's Speed."],
    [524,"Frost Breath","Ice","Special","Beautiful",10,60,0.9,-1,"Always results in a critical hit."],
    [525,"Dragon Tail","Dragon","Physical","Tough",10,60,0.9,-1,"In battles, the opponent switches. In the wild, the Pokémon runs."],
    [526,"Work Up","Normal","Status","Tough",30,0,"—",-1,"Raises user's Attack and Special Attack."],
    [527,"Electroweb","Electric","Special","Beautiful",15,55,0.95,-1,"Lowers opponent's Speed."],
    [528,"Wild Charge","Electric","Physical","Tough",15,90,1,-1,"User receives recoil damage."],
    [529,"Drill Run","Ground","Physical","Tough",10,80,0.95,-1,"High critical hit ratio."],
    [530,"Dual Chop","Dragon","Physical","Tough",15,40,0.9,-1,"Hits twice in one turn."],
    [531,"Heart Stamp","Psychic","Physical","Cute",25,60,1,8,"May cause flinching."],
    [532,"Horn Leech","Grass","Physical","Tough",10,75,1,-1,"User recovers half the HP inflicted on opponent."],
    [533,"Sacred Sword","Fighting","Physical","Cool",15,90,1,-1,"Ignores opponent's stat changes."],
    [534,"Razor Shell","Water","Physical","Cool",10,75,0.95,-1,"May lower opponent's Defense."],
    [535,"Heat Crash","Fire","Physical","Tough",10,0,1,-1,"The heavier the user, the stronger the attack."],
    [536,"Leaf Tornado","Grass","Special","Cool",10,65,0.9,-1,"May lower opponent's Accuracy."],
    [537,"Steamroller","Bug","Physical","Tough",20,65,1,-1,"May cause flinching."],
    [538,"Cotton Guard","Grass","Status","Cute",10,0,"—",-1,"Drastically raises user's Defense."],
    [539,"Night Daze","Dark","Special","Cool",10,85,0.95,-1,"May lower opponent's Accuracy."],
    [540,"Psystrike","Psychic","Special","Cool",10,100,1,-1,"Inflicts damage based on the target's Defense, not Special Defense."],
    [541,"Tail Slap","Normal","Physical","Cute",10,25,0.85,-1,"Hits 2-5 times in one turn."],
    [542,"Hurricane","Flying","Special","Tough",10,110,0.7,-1,"May confuse opponent."],
    [543,"Head Charge","Normal","Physical","Tough",15,120,1,-1,"User receives recoil damage."],
    [544,"Gear Grind","Steel","Physical","Clever",15,50,0.85,-1,"Hits twice in one turn."],
    [545,"Searing Shot","Fire","Special","Cool",5,100,1,-1,"May burn opponent."],
    [546,"Techno Blast","Normal","Special","Cool",5,120,1,-1,"Type depends on the Drive being held."],
    [547,"Relic Song","Normal","Special","Beautiful",10,75,1,-1,"May put the target to sleep."],
    [548,"Secret Sword","Fighting","Special","Beautiful",10,85,1,-1,"Inflicts damage based on the target's Defense, not Special Defense."],
    [549,"Glaciate","Ice","Special","Beautiful",10,65,0.95,-1,"Lowers opponent's Speed."],
    [550,"Bolt Strike","Electric","Physical","Beautiful",5,130,0.85,-1,"May paralyze opponent."],
    [551,"Blue Flare","Fire","Special","Beautiful",5,130,0.85,-1,"May burn opponent."],
    [552,"Fiery Dance","Fire","Special","Beautiful",10,80,1,-1,"May raise user's Special Attack."],
    [553,"Freeze Shock","Ice","Physical","Beautiful",5,140,0.9,-1,"Charges on first turn, attacks on second. May paralyze opponent."],
    [554,"Ice Burn","Ice","Special","Beautiful",5,140,0.9,-1,"Charges on first turn, attacks on second. May burn opponent."],
    [555,"Snarl","Dark","Special","Tough",15,55,0.95,-1,"Lowers opponent's Special Attack."],
    [556,"Icicle Crash","Ice","Physical","Beautiful",10,85,0.9,-1,"May cause flinching."],
    [557,"V-create","Fire","Physical","Cool",5,180,0.95,-1,"Lowers user's Defense, Special Defense and Speed."],
    [558,"Fusion Flare","Fire","Special","Beautiful",5,100,1,-1,"Power increases if Fusion Bolt is used in the same turn."],
    [559,"Fusion Bolt","Electric","Physical","Cool",5,100,1,-1,"Power increases if Fusion Flare is used in the same turn."],
    [560,"Flying Press","Fighting","Physical","Tough",10,100,0.95,-1,"Deals Fighting and Flying type damage."],
    [561,"Mat Block","Fighting","Status","Cool",10,0,"—",-1,"Protects teammates from damaging moves."],
    [562,"Belch","Poison","Special","Tough",10,120,0.9,-1,"User must have consumed a Berry."],
    [563,"Rototiller","Ground","Status","Tough",10,0,"—",-1,"Raises Attack and Special Attack of Grass-types."],
    [564,"Sticky Web","Bug","Status","Tough",20,0,"—",-1,"Lowers opponent's Speed when switching into battle."],
    [565,"Fell Stinger","Bug","Physical","Cool",25,50,1,-1,"Drastically raises user's Attack if target is KO'd."],
    [566,"Phantom Force","Ghost","Physical","Cool",10,90,1,-1,"Disappears on first turn, attacks on second. Can strike through Protect/Detect."],
    [567,"Trick-or-Treat","Ghost","Status","Cute",20,0,1,-1,"Adds Ghost type to opponent."],
    [568,"Noble Roar","Normal","Status","Tough",30,0,1,-1,"Lowers opponent's Attack and Special Attack."],
    [569,"Ion Deluge","Electric","Status","Beautiful",25,0,"—",-1,"Changes Normal-type moves to Electric-type."],
    [570,"Parabolic Charge","Electric","Special","Clever",20,65,1,-1,"User recovers half the HP inflicted on opponent."],
    [571,"Forest's Curse","Grass","Status","Clever",20,0,1,-1,"Adds Grass type to opponent."],
    [572,"Petal Blizzard","Grass","Physical","Beautiful",15,90,1,-1,"Hits all adjacent Pokémon."],
    [573,"Freeze-Dry","Ice","Special","Beautiful",20,70,1,-1,"May freeze opponent. Super effective against Water types."],
    [574,"Disarming Voice","Fairy","Special","Cute",15,40,"—",-1,"Ignores Accuracy and Evasiveness."],
    [575,"Parting Shot","Dark","Status","Cool",20,0,1,-1,"Lowers opponent's Attack and Special Attack then switches out."],
    [576,"Topsy-Turvy","Dark","Status","Clever",20,0,"—",-1,"Reverses stat changes of opponent."],
    [577,"Draining Kiss","Fairy","Special","Cute",10,50,1,-1,"User recovers most damage inflicted on opponent."],
    [578,"Crafty Shield","Fairy","Status","Clever",10,0,"—",-1,"Protects the Pokémon from status moves."],
    [579,"Flower Shield","Fairy","Status","Beautiful",10,0,"—",-1,"Raises Defense of all Grass-type Pokémon on the field."],
    [580,"Grassy Terrain","Grass","Status","Beautiful",10,0,"—",-1,"Restores a little HP of all Pokémon for 5 turns."],
    [581,"Misty Terrain","Fairy","Status","Beautiful",10,0,"—",-1,"Protects the field from status conditions for 5 turns."],
    [582,"Electrify","Electric","Status","Clever",20,0,"—",-1,"Changes the target's move to Electric type."],
    [583,"Play Rough","Fairy","Physical","Cute",10,90,0.9,-1,"May lower opponent's Attack."],
    [584,"Fairy Wind","Fairy","Special","Beautiful",30,40,1,0,"A damaging attack."],
    [585,"Moonblast","Fairy","Special","Beautiful",15,95,1,-1,"May lower opponent's Special Attack."],
    [586,"Boomburst","Normal","Special","Tough",10,140,1,-1,"Hits all adjacent Pokémon."],
    [587,"Fairy Lock","Fairy","Status","Clever",10,0,"—",-1,"Prevents fleeing in the next turn."],
    [588,"King's Shield","Steel","Status","Cool",10,0,"—",-1,"Protects the user and lowers opponent's Attack on contact."],
    [589,"Play Nice","Normal","Status","Cute",20,0,"—",-1,"Lowers opponent's Attack. Always hits."],
    [590,"Confide","Normal","Status","Cute",20,0,"—",-1,"Lowers opponent's Special Attack."],
    [591,"Diamond Storm","Rock","Physical","Beautiful",5,100,0.95,-1,"May raise user's Defense"],
    [592,"Steam Eruption","Water","Special","Beautiful",5,110,0.95,-1,"May burn opponent."],
    [593,"Hyperspace Hole","Psychic","Special","Clever",5,80,"—",-1,"Can strike through Protect/Detect."],
    [594,"Water Shuriken","Water","Special","Cool",20,15,1,-1,"Hits 2-5 times in one turn."],
    [595,"Mystical Fire","Fire","Special","Beautiful",10,75,1,-1,"Lowers opponent's Special Attack."],
    [596,"Spiky Shield","Grass","Status","Tough",10,0,"—",-1,"Protects the user and inflicts damage on contact."],
    [597,"Aromatic Mist","Fairy","Status","Beautiful",20,0,"—",-1,"Raises Special Defense of allies."],
    [598,"Eerie Impulse","Electric","Status","Clever",15,0,1,-1,"Sharply lowers opponent's Special Attack."],
    [599,"Venom Drench","Poison","Status","Clever",20,0,1,-1,"Lowers poisoned opponent's Special Attack and Speed."],
    [600,"Powder","Bug","Status","Clever",20,0,1,-1,"Damages Pokémon using Fire-type moves."],
    [601,"Geomancy","Fairy","Status","Beautiful",10,0,"—",-1,"Charges on first turn, sharply raises user's Sp. Attack, Sp. Defense and Speed on the second."],
    [602,"Magnetic Flux","Electric","Status","Clever",20,0,"—",-1,"Raises Defense and Sp. Defense of Plus/Minus Pokémon."],
    [603,"Happy Hour","Normal","Status","Cute",30,0,"—",7,"Doubles prize money from trainer battles."],
    [604,"Electric Terrain","Electric","Status","Clever",10,0,"—",-1,"Prevents all Pokémon from falling asleep for 5 turns."],
    [605,"Dazzling Gleam","Fairy","Special","Beautiful",10,80,1,-1,"Hits all adjacent opponents."],
    [606,"Celebrate","Normal","Status","Cute",40,0,"—",-1,"The Pokémon congratulates you on your special day. No battle effect."],
    [607,"Hold Hands","Normal","Status","Cute",40,0,"—",-1,"Makes the user and an ally very happy."],
    [608,"Baby-Doll Eyes","Fairy","Status","Cute",30,0,1,-1,"Always goes first. Lowers the target's attack."],
    [609,"Nuzzle","Electric","Physical","Cute",20,20,1,-1,"Paralyzes opponent."],
    [610,"Hold Back","Normal","Physical","Cool",40,40,1,-1,"Always leaves opponent with at least 1 HP."],
    [611,"Infestation","Bug","Special","Cute",20,20,1,-1,"Traps opponent, damaging them for 4-5 turns."],
    [612,"Power-Up Punch","Fighting","Physical","Tough",20,40,1,-1,"Raises Attack."],
    [613,"Oblivion Wing","Flying","Special","Cool",10,80,1,-1,"User recovers most of the HP inflicted on opponent."],
    [614,"Thousand Arrows","Ground","Physical","Beautiful",10,90,1,-1,"Makes Flying-type Pokémon vulnerable to Ground moves."],
    [615,"Thousand Waves","Ground","Physical","Tough",10,90,1,-1,"Opponent cannot flee or switch."],
    [616,"Land's Wrath","Ground","Physical","Beautiful",10,90,1,0,"A damaging attack."],
    [617,"Light of Ruin","Fairy","Special","Beautiful",5,140,0.9,-1,"User receives recoil damage."],
    [618,"Origin Pulse","Water","Special","Beautiful",10,110,0.85,-1,"Hits all adjacent opponents."],
    [619,"Precipice Blades","Ground","Physical","Cool",10,120,0.85,-1,"Hits all adjacent opponents."],
    [620,"Dragon Ascent","Flying","Physical","Beautiful",5,120,1,-1,"Lowers user's Defense and Special Defense."],
    [621,"Hyperspace Fury","Dark","Physical","Tough",5,100,"—",-1,"Lowers user's Defense. Can strike through Protect/Detect."],
    [622,"Breakneck Blitz","Normal","Physical","Tough",1,0,"—",-1,"Normal type Z-Move."],
    [623,"Breakneck Blitz","Normal","Special","Tough",1,0,"—",-1,"Normal type Z-Move."],
    [624,"All-Out Pummeling","Fighting","Physical","Tough",1,0,"—",-1,"Fighting type Z-Move."],
    [625,"All-Out Pummeling","Fighting","Special","Tough",1,0,"—",-1,"Fighting type Z-Move."],
    [626,"Supersonic Skystrike","Flying","Physical","Cool",1,0,"—",-1,"Flying type Z-Move."],
    [627,"Supersonic Skystrike","Flying","Special","Cool",1,0,"—",-1,"Flying type Z-Move."],
    [628,"Acid Downpour","Poison","Physical","Clever",1,0,"—",-1,"Poison type Z-Move."],
    [629,"Acid Downpour","Poison","Special","Clever",1,0,"—",-1,"Poison type Z-Move."],
    [630,"Tectonic Rage","Ground","Physical","Tough",1,0,"—",-1,"Ground type Z-Move."],
    [631,"Tectonic Rage","Ground","Special","Tough",1,0,"—",-1,"Ground type Z-Move."],
    [632,"Continental Crush","Rock","Physical","Tough",1,0,"—",-1,"Rock type Z-Move."],
    [633,"Continental Crush","Rock","Special","Tough",1,0,"—",-1,"Rock type Z-Move."],
    [634,"Savage Spin-Out","Bug","Physical","Tough",1,0,"—",-1,"Bug type Z-Move."],
    [635,"Savage Spin-Out","Bug","Special","Tough",1,0,"—",-1,"Bug type Z-Move."],
    [636,"Never-Ending Nightmare","Ghost","Physical","Clever",1,0,"—",-1,"Ghost type Z-Move."],
    [637,"Never-Ending Nightmare","Ghost","Special","Clever",1,0,"—",-1,"Ghost type Z-Move."],
    [638,"Corkscrew Crash","Steel","Physical","Tough",1,0,"—",-1,"Steel type Z-Move."],
    [639,"Corkscrew Crash","Steel","Special","Tough",1,0,"—",-1,"Steel type Z-Move."],
    [640,"Inferno Overdrive","Fire","Physical","Beautiful",1,0,"—",-1,"Fire type Z-Move."],
    [641,"Inferno Overdrive","Fire","Special","Beautiful",1,0,"—",-1,"Fire type Z-Move."],
    [642,"Hydro Vortex","Water","Physical","Beautiful",1,0,"—",-1,"Water type Z-Move."],
    [643,"Hydro Vortex","Water","Special","Beautiful",1,0,"—",-1,"Water type Z-Move."],
    [644,"Bloom Doom","Grass","Physical","Cute",1,0,"—",-1,"Grass type Z-Move."],
    [645,"Bloom Doom","Grass","Special","Cute",1,0,"—",-1,"Grass type Z-Move."],
    [646,"Gigavolt Havoc","Electric","Physical","Cool",1,0,"—",-1,"Electric type Z-Move."],
    [647,"Gigavolt Havoc","Electric","Special","Cool",1,0,"—",-1,"Electric type Z-Move."],
    [648,"Shattered Psyche","Psychic","Physical","Clever",1,0,"—",-1,"Psychic type Z-Move."],
    [649,"Shattered Psyche","Psychic","Special","Clever",1,0,"—",-1,"Psychic type Z-Move."],
    [650,"Subzero Slammer","Ice","Physical","Beautiful",1,0,"—",-1,"Ice type Z-Move."],
    [651,"Subzero Slammer","Ice","Special","Beautiful",1,0,"—",-1,"Ice type Z-Move."],
    [652,"Devastating Drake","Dragon","Physical","Tough",1,0,"—",-1,"Dragon type Z-Move."],
    [653,"Devastating Drake","Dragon","Special","Tough",1,0,"—",-1,"Dragon type Z-Move."],
    [654,"Black Hole Eclipse","Dark","Physical","Clever",1,0,"—",-1,"Dark type Z-Move."],
    [655,"Black Hole Eclipse","Dark","Special","Clever",1,0,"—",-1,"Dark type Z-Move."],
    [656,"Twinkle Tackle","Fairy","Physical","Cute",1,0,"—",-1,"Fairy type Z-Move."],
    [657,"Twinkle Tackle","Fairy","Special","Cute",1,0,"—",-1,"Fairy type Z-Move."],
    [658,"Catastropika","Electric","Physical","Cute",1,210,"—",-1,"Pikachu-exclusive Z-Move."],
    [659,"Shore Up","Ground","Status","Clever",10,0,"—",-1,"The user regains up to half of its max HP. It restores more HP in a sandstorm."],
    [660,"First Impression","Bug","Physical","Cool",10,90,1,-1,"Although this move has great power, it only works the first turn the user is in battle."],
    [661,"Baneful Bunker","Poison","Status","Clever",10,0,"—",-1,"Protects the user and poisons opponent on contact."],
    [662,"Spirit Shackle","Ghost","Physical","Clever",10,80,1,-1,"Prevents the opponent switching out."],
    [663,"Darkest Lariat","Dark","Physical","Cool",10,85,1,-1,"Ignores opponent's stat changes."],
    [664,"Sparkling Aria","Water","Special","Beautiful",10,90,1,-1,"Heals the burns of its target."],
    [665,"Ice Hammer","Ice","Physical","Tough",10,100,0.9,-1,"The user swings and hits with its strong, heavy fist. It lowers the user's Speed, however."],
    [666,"Floral Healing","Fairy","Status","Cute",10,0,"—",-1,"The user restores the target's HP by up to half of its max HP. It restores more HP when the terrain is grass."],
    [667,"High Horsepower","Ground","Physical","Tough",10,95,0.95,-1,"The user fiercely attacks the target using its entire body."],
    [668,"Strength Sap","Grass","Status","Clever",10,0,1,-1,"The user restores its HP by the same amount as the target's Attack stat. It also lowers the target's Attack stat."],
    [669,"Solar Blade","Grass","Physical","Beautiful",10,125,1,-1,"Charges on first turn, attacks on second."],
    [670,"Leafage","Grass","Physical","Cool",40,40,1,-1,"Strikes opponent with leaves."],
    [671,"Spotlight","Normal","Status","Cute",15,0,"—",-1,"The user shines a spotlight on the target so that only the target will be attacked during the turn."],
    [672,"Toxic Thread","Poison","Status","Clever",20,0,1,-1,"The user shoots poisonous threads to poison the target and lower the target's Speed stat."],
    [673,"Laser Focus","Normal","Status","Clever",30,0,"—",-1,"User's next attack is guaranteed to result in a critical hit."],
    [674,"Gear Up","Steel","Status","Clever",20,0,"—",-1,"The user engages its gears to raise the Attack and Sp. Atk stats of ally Pokémon with the Plus or Minus Ability."],
    [675,"Throat Chop","Dark","Physical","Cool",15,80,1,-1,"Prevents use of sound moves for two turns."],
    [676,"Pollen Puff","Bug","Special","Cute",15,90,1,-1,"The user attacks the enemy with a pollen puff that explodes. If the target is an ally, it gives the ally a pollen puff that restores its HP instead."],
    [677,"Anchor Shot","Steel","Physical","Tough",20,80,1,-1,"The user entangles the target with its anchor chain while attacking. The target becomes unable to flee."],
    [678,"Psychic Terrain","Psychic","Status","Clever",10,0,"—",-1,"Prevents priority moves from being used for 5 turns."],
    [679,"Lunge","Bug","Physical","Cool",15,80,1,-1,"The user makes a lunge at the target, attacking with full force. This also lowers the target's Attack stat."],
    [680,"Fire Lash","Fire","Physical","Beautiful",15,80,1,-1,"The user strikes the target with a burning lash. This also lowers the target's Defense stat."],
    [681,"Power Trip","Dark","Physical","Tough",10,20,1,-1,"The user boasts its strength and attacks the target. The more the user's stats are raised, the greater the move's power."],
    [682,"Burn Up","Fire","Special","Beautiful",5,130,1,-1,"To inflict massive damage, the user burns itself out. After using this move, the user will no longer be Fire type."],
    [683,"Speed Swap","Psychic","Status","Clever",10,0,"—",-1,"The user exchanges Speed stats with the target."],
    [684,"Smart Strike","Steel","Physical","Clever",10,70,"—",-1,"The user stabs the target with a sharp horn. This attack never misses."],
    [685,"Purify","Poison","Status","Cute",20,0,"—",-1,"The user heals the target's status condition. If the move succeeds, it also restores the user's own HP."],
    [686,"Revelation Dance","Normal","Special","Beautiful",15,90,1,-1,"Type changes based on Oricorio's form."],
    [687,"Core Enforcer","Dragon","Special","Tough",10,100,1,-1,"Scorches a 'Z' pattern on the ground."],
    [688,"Trop Kick","Grass","Physical","Beautiful",15,70,1,-1,"Lowers opponent's Attack."],
    [689,"Instruct","Psychic","Status","Clever",15,0,"—",-1,"Allows an ally to use a move instead."],
    [690,"Beak Blast","Flying","Physical","Tough",15,100,1,-1,"The user first heats up its beak, and then it attacks the target. Making direct contact with the Pokémon while it's heating up its beak results in a burn."],
    [691,"Clanging Scales","Dragon","Special","Tough",5,110,1,-1,"Lowers user's Defense."],
    [692,"Dragon Hammer","Dragon","Physical","Tough",15,90,1,-1,"The user uses its body like a hammer to attack the target and inflict damage."],
    [693,"Brutal Swing","Dark","Physical","Tough",20,60,1,-1,"The user swings its body around violently to inflict damage on everything in its vicinity."],
    [694,"Aurora Veil","Ice","Status","Beautiful",20,0,"—",-1,"Halves damage from Physical and Special attacks for five turns, only in hail."],
    [695,"Sinister Arrow Raid","Ghost","Physical","Clever",1,180,"—",-1,"Decidueye-exclusive Z-Move."],
    [696,"Malicious Moonsault","Dark","Physical","Tough",1,180,"—",-1,"Incineroar-exclusive Z-Move."],
    [697,"Oceanic Operetta","Water","Special","Cute",1,195,"—",-1,"Primarina-exclusive Z-Move."],
    [698,"Guardian of Alola","Fairy","Special","Beautiful",1,0,"—",-1,"Tapu-exclusive Z-move. Cuts opponent's HP by 75%."],
    [699,"Soul-Stealing 7-Star Strike","Ghost","Physical","Tough",1,195,"—",-1,"Marshadow-exclusive Z-Move."],
    [700,"Stoked Sparksurfer","Electric","Special","Cool",1,175,"—",-1,"Alolan Raichu-exclusive Electric type Z-Move."],
    [701,"Pulverizing Pancake","Normal","Physical","Tough",1,210,"—",-1,"Snorlax-exclusive Normal type Z-Move."],
    [702,"Extreme Evoboost","Normal","Status","Cute",1,0,"—",-1,"Eevee-exclusive Z-Move. Sharply raises all stats."],
    [703,"Genesis Supernova","Psychic","Special","Cute",1,185,"—",-1,"Mew-exclusive Z-Move."],
    [704,"Shell Trap","Fire","Special","Clever",5,150,1,-1,"Deals more damage to opponent if hit by a Physical move."],
    [705,"Fleur Cannon","Fairy","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."],
    [706,"Psychic Fangs","Psychic","Physical","Tough",10,85,1,-1,"The user bites the target with its psychic capabilities. This can also destroy Light Screen and Reflect."],
    [707,"Stomping Tantrum","Ground","Physical","Tough",10,75,1,-1,"Driven by frustration, the user attacks the target. If the user's previous move has failed, the power of this move doubles."],
    [708,"Shadow Bone","Ghost","Physical","Tough",10,85,1,-1,"The user attacks by beating the target with a bone that contains a spirit. This may also lower the target's Defense stat."],
    [709,"Accelerock","Rock","Physical","Cool",20,40,1,-1,"User attacks first."],
    [710,"Liquidation","Water","Physical","Tough",10,85,1,-1,"The user slams into the target using a full-force blast of water. This may also lower the target's Defense stat."],
    [711,"Prismatic Laser","Psychic","Special","Beautiful",10,160,1,-1,"The user shoots powerful lasers using the power of a prism. The user can't move on the next turn."],
    [712,"Spectral Thief","Ghost","Physical","Clever",10,90,1,-1,"The user hides in the target's shadow, steals the target's stat boosts, and then attacks."],
    [713,"Sunsteel Strike","Steel","Physical","Tough",5,100,1,-1,"Ignores the target's ability."],
    [714,"Moongeist Beam","Ghost","Special","Beautiful",5,100,1,-1,"Ignores the target's ability."],
    [715,"Tearful Look","Normal","Status","Cute",20,0,"—",-1,"Lowers the target's attack stats, penetrating protection."],
    [716,"Zing Zap","Electric","Physical","Cool",10,80,1,-1,"A strong electric blast crashes down on the target, giving it an electric shock. This may also make the target flinch."],
    [717,"Nature's Madness","Fairy","Special","Tough",10,0,0.9,-1,"Halves the foe's HP."],
    [718,"Multi-Attack","Normal","Physical","Clever",10,90,1,-1,"Type matches user's current type."],
    [719,"10,000,000 Volt Thunderbolt","Electric","Special","Cute",1,195,"—",-1,"Pikachu-exclusive Z-Move."],
    [720,"Mind Blown","Fire","Special","Clever",5,150,1,-1,"User receives recoil damage."],
    [721,"Plasma Fists","Electric","Physical","Tough",15,100,1,-1,"Changes Normal-type moves to Electric-type moves."],
    [722,"Photon Geyser","Psychic","Special","Beautiful",5,100,1,-1,"Uses Attack or Special Attack stat, whichever is higher."],
    [723,"Light That Burns the Sky","Psychic","Special","Beautiful",1,200,"—",-1,"Ultra Necrozma-exclusive Z-Move. Ignores target's ability; uses highest Attack stat."],
    [724,"Searing Sunraze Smash","Steel","Special","Tough",1,200,"—",-1,"Solgaleo-exclusive Z-Move."],
    [725,"Menacing Moonraze Maelstrom","Ghost","Special","Beautiful",1,200,"—",-1,"Lunala-exclusive Z-Move."],
    [726,"Let's Snuggle Forever","Fairy","Physical","Cute",1,190,"—",-1,"Mimikyu-exclusive Z-Move."],
    [727,"Splintered Stormshards","Rock","Physical","Cool",1,190,"—",-1,"Lycanroc-exclusive Z-Move."],
    [728,"Clangorous Soulblaze","Dragon","Special","Tough",1,185,"—",-1,"Kommo-o exclusive Z-Move."],
    [729,"Zippy Zap","Electric","Physical","Cute",10,80,1,-1,"Strikes first, and raises evasion."],
    [730,"Splishy Splash","Water","Special","Cute",15,90,1,-1,"May paralyze opponent."],
    [731,"Floaty Fall","Flying","Physical","Cute",15,90,0.95,-1,"May cause flinching."],
    [732,"Pika Papow","Electric","Special","Cute",20,0,"—",-1,"Power increases when player's bond is stronger."],
    [733,"Bouncy Bubble","Water","Special","Cute",15,90,1,-1,"User recovers half the HP inflicted on opponent."],
    [734,"Buzzy Buzz","Electric","Special","Cute",15,90,1,-1,"Paralyzes the opponent."],
    [735,"Sizzly Slide","Fire","Physical","Cute",15,90,1,-1,"Burns the opponent."],
    [736,"Glitzy Glow","Psychic","Special","Cute",15,90,1,-1,"Reduces damage from Special attacks."],
    [737,"Baddy Bad","Dark","Special","Cute",15,90,1,-1,"Reduces damage from Physical attacks."],
    [738,"Sappy Seed","Grass","Physical","Cute",15,90,1,-1,"Drains HP from opponent each turn."],
    [739,"Freezy Frost","Ice","Special","Cute",15,90,1,-1,"Resets all stat changes."],
    [740,"Sparkly Swirl","Fairy","Special","Cute",15,90,1,-1,"Cures all status problems in the party Pokémon."],
    [741,"Veevee Volley","Normal","Physical","Cute",20,0,"—",-1,"Power increases when player's bond is stronger."],
    [742,"Double Iron Bash","Steel","Physical","Tough",5,60,1,-1,"Hits twice in one turn; may cause flinching."],
    #OC Moves: Donut Steel
    [743,"Chrysalize","Bug","Status","Beautiful",10,0,"—",-1,"User sleeps for 2 turns, but heals fully and increases defenses."],
    [744,"Enshroud","Dark","Status","Clever",10,0,"—",-1,"Protects, ups evasion if the foe doesn't contact. Fails if consecutive."],
    [745,"Legacy","Dragon","Status","Tough",5,0,1,-1,"User moves first, flinching then paralyzing foe. Only usable on first turn, fails against fairies or foes that can't be intimidated."],
    [746,"Energize","Electric","Status","Clever",20,0,"—",-1,"Raises user's attack stats and next Electric move's power increases."],
    [747,"Ardent Gaze","Fairy","Status","Cute",15,0,1,-1,"The opponent becomes less likely to attack."],
    [748,"Disabling Poke","Fighting","Physical","Clever",30,40,1,-1,"User attacks first, disabling the foe's last used move for a few turns."],
    [749,"Steady Flame","Fire","Status","Beautiful",10,0,1,-1,"Burns opponent."],
    [750,"Wing It","Flying","Status","Cool",30,0,"—",-1,"Continually applies large random stat changes, and lesser stat decreases."],
    [751,"Deathless","Ghost","Status","Beautiful",10,0,"—",-1,"Recovers health instead of fainting, but may fail if used consecutively."],
    [752,"Bark Up","Grass","Status","Tough",20,0,"—",-1,"User restores HP each turn, and raises defenses, but cannot escape."],
    [753,"Burial Ground", "Ground","Status","Clever",10,0,"—",-1,"Slows and hurts grounded non-Ground and Ghost-types for 5 turns."],
    [754,"Slow Freeze", "Ice","Status","Cool",10,0,.85,-1,"Moves later, but freezes the foe."],
    [755,"Simple World", "Normal","Status","Clever",10,0,"—",-1,"All grounded Pokémon become Normal-type for 5 turns."],
    [756,"Bad Breath","Poison","Status","Tough",10,0,.90,-1,"Badly poisons opponent. If it can't, paralyzes. If it can't, confuses."],
    [757,"Clear Mind","Psychic","Status","Clever",20,0,1,-1,"Cures all non-volatile status conditions, and resets stat changes."],
    [758,"Splinter Shield","Rock","Status","Tough",10,0,"—",-1,"Protects, and creates rocky shards on contact. Fails if consecutive."],
    [759,"Metallize","Steel","Status","Cool",20,0,1,-1,"Adds Steel type to a Pokémon."],
    [760,"Healing Spring","Water","Status","Beautiful",5,0,"—",-1,"Makes it rain for 5 turns, and restores a little bit of health every turn."],
    #galar/paldea moves
    [761,"Breaking Swipe","Dragon","Physical","Tough",15,60,1,-1,"Hits adjacent opponents, lowering attack."],
    [762,"Hyper Drill","Normal","Physical","Tough",5,100,1,-1,"Hits through protecting moves."],
    [763,"Silk Trap","Bug","Status","Clever",10,0,1,-1,"Protects against damage, and slows foes who make contact."],
    #OC Moves: And I claim to hate Ash-Greninja
    [764,"Liberage","Normal","Status","Cool",1,0,"-",-1,"Slays kings."],
    #galar/paldea moves:
    [765,"Branch Poke","Grass","Physical","Tough",40,40,1,-1,"The user attacks the target by poking it with a sharply pointed branch."],
    [766,"No Retreat","Fighting","Status","Tough",5,0,"-",-1,"Boosts all stats, but locks in. Fails if already locked in."],
    [767,"Scale Shot","Dragon","Physical","Cool",20,25,.9,-1,"Hits 2-5 times in one turn."],
    [768,"Headlong Rush","Ground","Physical","Tough",5,120,1,-1,"Lowers user's Defense and Special Defense."],
    [769,"Spirit Break","Fairy","Physical","Clever",15,75,1,-1,"Lowers target's Special Attack."],
    [770,"Flip Turn","Water","Physical","Cool",20,60,1,-1,"User switches out immediately after attacking."],
    [771,"Aqua Cutter","Water","Physical","Cool",20,70,1,-1,"High critical rate."],
    [772,"Fillet Away","Normal","Status","Clever",20,0,"-",-1,"Reduces health to boost stats."],
    [773,"Salt Cure","Rock","Physical","Clever",15,40,1,-1,"Does damage over time, especially to Steel/Water types."],
    #the dumbest thing I've ever done
    [774, "Stone Cold Stunner","Fighting","Status","Tough",1,0,"-",-1,"Causes you to lose."],
    #i have no idea where this move came from
    [775, "Life Dew","Water","Status","Beautiful",10,0,"-",-1,"Restores self and allies' health."],
    #Paldean move
    [776, "Rage Fist","Ghost","Physical","Tough",10,50,1,-1,"Gets more powerful when you get hit."],
    #galarian move
    [777, "Overdrive", "Electric", "Special", "Cool", 10, 80, 1, -1, "Hits all adjacent foes."],
    #paldean move. I probably should have organized this better ahead of time, huh?
    [778, "Skitter Smack", "Bug", "Physical", "Clever", 10, 70, .9, -1, "Lowers foe's Special Attack."],
    #galarian move. I guess I'm just going to keep updating this log of my poor decisions
    [779, "Doodle", "Normal", "Status", "Clever", 10, 0, 1, -1, "The user copies the foe's ability onto itself and its allies."],
    #OC Mooooove!
    [780, "nothing", "Normal", "Status", "Cool", 99, 0, 1, -1, "Does nothing, unless you're Luigi."],
    #A Paldean move that _feels_ like an OC move. Shit's broken.
    [781, "Shed Tail", "Normal", "Status", "Clever", 10, 0, 1, -1, "Creates a substitute, then switches out."],
    #This move is why Rillaboom is a Tapu
    [782, "Trailblaze", "Grass", "Physical", "Cool", 20, 50, 1, -1, "Inflicts damage and raises the user's Speed by one stage."],
    #and people still don't use ice types
    [783, "Snowscape", "Ice", "Status", "Beautiful", 10, 0,"-",-1, "Ice types have boosted Defense for 5 turns."],
    # Ogerpon exclusive move.
    [784, "Ivy Cudgel","Grass","Physical","Tough",10,100,1,-1,"Increased crit rate, changes type if used by Ogerpon."],
    #exclusive to Duplica's ditto
    [785, "Kasa's Transform","Normal","Status","Clever",10,0,"-",-1,"User takes on the form and attacks of a very powerful Pokémon."],
    #actual moves
    [786, "Glaive Rush","Dragon","Physical","Tough",5,120,1,-1,"Deals massive damage, but leaves the user vulnerable until its next turn."],
    [787, "Psyshield Bash","Psychic","Physical","Clever",10,70,.9,-1,"Inflicts damage and raises the user's defense."],
    [788,"Kowtow Cleave","Dark","Physical","Clever",10,85,"—",-1,"Ignores Accuracy and Evasiveness."],
    [789, "Dragon Darts","Dragon","Physical","Clever",10,50,1,-1,"#FIX THIS: Program this later"],
    [790, "Gigaton Hammer","Steel","Physical","Tough",5,160,1,-1,"Does tremendous damage, but can't be used twice in a row."],
    [791, "Eerie Spell","Psychic","Special","Clever",5,80,1,-1,"Does damage, and reduces the foe's PP."],
    [792, "False Surrender","Dark","Physical","Clever",10,80,"—",-1,"Ignores Accuracy and Evasiveness."],
    [793, "Shell Side Arm","Poison","Special","Clever",10,80,1,-1,"Will do either Physical or Special damage, whichever is more effective. May poison."],
    [794, "Last Respects","Ghost","Physical","Cute",10,50,1,-1,"Will do more damage every time an ally faints."],
    [795, "Octolock","Fighting","Status","Tough",15,0,1,-1,"Prevents opponent from switching and lowers defenses at end of turn."],
    [796, "Teatime","Normal","Status","Beautiful",10,0,"-",-1,"All Pokémon on the field immediately consume their berries."],
    [797, "Strange Steam","Fairy","Special","Beautiful",10,90,.95,-1,"May confuse the target."],
    [798, "Dual Wingbeat","Flying","Physical","Tough",10,40,.9,-1,"Hits twice in one turn."],
    [799,"Obstruct","Dark","Status","Tough",10,0,"—",-1,"Protects the user, and lowers foe's defense on contact. May fail if used consecutively."]
    
    
    
    
    
    ]
    
    #movedex/      Name/Type/Category/Contest/PP/Power/Accuracy/Effect/Description
    #      0          1    2        3       4  5     6        7      8           9
