init python:
    movepowerdex = {
        "Pound": 50,
        "Karate Chop": 60,
        "Double Slap": 49,
        "Comet Punch": 56,
        "Mega Punch": 68,
        "Pay Day": 50,
        "Fire Punch": 85,
        "Ice Punch": 85,
        "Thunder Punch": 85,
        "Scratch": 40,
        "Vise Grip": 55,
        "Guillotine": 150,
        "Razor Wind": 110,
        "Swords Dance": 90,
        "Cut": 48,
        "Gust": 50,
        "Wing Attack": 60,
        "Whirlwind": 10,
        "Fly": 96,
        "Bind": 23,
        "Slam": 60,
        "Vine Whip": 45,
        "Stomp": 75,
        "Double Kick": 40,
        "Mega Kick": 90,
        "Jump Kick": 105,
        "Rolling Kick": 61,
        "Sand Attack": 40,
        "Headbutt": 80,
        "Horn Attack": 65,
        "Fury Attack": 49,
        "Horn Drill": 150,
        "Tackle": 40,
        "Body Slam": 95,
        "Wrap": 24,
        "Take Down": 87,
        "Thrash": 150,
        "Double-Edge": 130,
        "Tail Whip": 60,
        "Poison Sting": 25,
        "Twineedle": 35,
        "Pin Missile": 82,
        "Leer": 60,
        "Bite": 70,
        "Growl": 40,
        "Roar": 10,
        "Sing": 10,
        "Supersonic": 10,
        "Sonic Boom": 10,
        "Disable": 10,
        "Acid": 100,
        "Ember": 50,
        "Flamethrower": 100,
        "Mist": 30,
        "Water Gun": 40,
        "Hydro Pump": 88,
        "Surf": 120,
        "Ice Beam": 100,
        "Blizzard": 107,
        "Psybeam": 75,
        "Bubble Beam": 105,
        "Aurora Beam": 105,
        "Hyper Beam": 145,
        "Peck": 35,
        "Drill Peck": 80,
        "Submission": 74,
        "Low Kick": 80,
        "Counter": 120,
        "Seismic Toss": 10,
        "Strength": 80,
        "Absorb": 30,
        "Mega Drain": 50,
        "Leech Seed": 60,
        "Growth": 90,
        "Razor Leaf": 83,
        "Solar Beam": 130,
        "Poison Powder": 10,
        "Stun Spore": 10,
        "Sleep Powder": 10,
        "Petal Dance": 150,
        "String Shot": 90,
        "Dragon Rage": 80,
        "Fire Spin": 40,
        "Thunder Shock": 50,
        "Thunderbolt": 100,
        "Thunder Wave": 10,
        "Thunder": 87,
        "Rock Throw": 45,
        "Earthquake": 130,
        "Fissure": 150,
        "Dig": 90,
        "Toxic": 10,
        "Confusion": 60,
        "Psychic": 130,
        "Hypnosis": 10,
        "Meditate": 60,
        "Agility": 90,
        "Quick Attack": 50,
        "Rage": 30,
        "Teleport": 30,
        "Night Shade": 10,
        "Mimic": 10,
        "Screech": 70,
        "Double Team": 60,
        "Life Dew": 80,
        "Recover": 100,
        "Harden": 60,
        "Minimize": 90,
        "Smokescreen": 40,
        "Confuse Ray": 10,
        "Withdraw": 60,
        "Defense Curl": 60,
        "Barrier": 90,
        "Light Screen": 30,
        "Haze": 30,
        "Reflect": 30,
        "Focus Energy": 30,
        "Bide": 30,
        "Metronome": 30,
        "Mirror Move": 10,
        "Self Destruct": 230,
        "Egg Bomb": 75,
        "Lick": 40,
        "Smog": 31,
        "Sludge": 75,
        "Bone Club": 66,
        "Fire Blast": 104,
        "Waterfall": 90,
        "Clamp": 40,
        "Swift": 30,
        "Skull Bash": 140,
        "Spike Cannon": 70,
        "Constrict": 50,
        "Amnesia": 90,
        "Kinesis": 40,
        "Soft-Boiled": 100,
        "High Jump Kick": 127,
        "Glare": 10,
        "Dream Eater": 110,
        "Poison Gas": 30,
        "Barrage": 49,
        "Leech Life": 90,
        "Lovely Kiss": 10,
        "Sky Attack": 136,
        "Transform": 10,
        "Bubble": 60,
        "Dizzy Punch": 80,
        "Spore": 100,
        "Flash": 40,
        "Psywave": 10,
        "Splash": 30,
        "Acid Armor": 90,
        "Crabhammer": 100,
        "Explosion": 280,
        "Fury Swipes": 54,
        "Bonemerang": 55,
        "Rest": 30,
        "Rock Slide": 98,
        "Hyper Fang": 82,
        "Sharpen": 60,
        "Conversion": 30,
        "Tri Attack": 90,
        "Super Fang": 10,
        "Slash": 80,
        "Substitute": 30,
        "Struggle": 30,
        "Sketch": 10,
        "Triple Kick": 19,
        "Thief": 70,
        "Spider Web": 10,
        "Mind Reader": 10,
        "Nightmare": 10,
        "Flame Wheel": 70,
        "Snore": 60,
        "Curse": 30,
        "Flail": 80,
        "Conversion 2": 10,
        "Aeroblast": 105,
        "Cotton Spore": 90,
        "Reversal": 10,
        "Spite": 10,
        "Powder Snow": 70,
        "Protect": 60,
        "Mach Punch": 60,
        "Scary Face": 70,
        "Feint Attack": 10,
        "Sweet Kiss": 10,
        "Belly Drum": 30,
        "Sludge Bomb": 100,
        "Mud-Slap": 60,
        "Octazooka": 96,
        "Spikes": 30,
        "Zap Cannon": 70,
        "Foresight": 10,
        "Destiny Bond": 30,
        "Perish Song": 80,
        "Icy Wind": 113,
        "Detect": 30,
        "Bone Rush": 88,
        "Lock-On": 10,
        "Outrage": 150,
        "Sandstorm": 30,
        "Giga Drain": 85,
        "Endure": 30,
        "Charm": 80,
        "Rollout": 50,
        "False Swipe": 50,
        "Swagger": 70,
        "Milk Drink": 80,
        "Spark": 75,
        "Fury Cutter": 48,
        "Steel Wing": 103,
        "Mean Look": 10,
        "Attract": 10,
        "Sleep Talk": 30,
        "Heal Bell": 30,
        "Return": 80,
        "Present": 10,
        "Frustration": 80,
        "Safeguard": 30,
        "Pain Split": 70,
        "Sacred Fire": 105,
        "Magnitude": 60,
        "Dynamic Punch": 60,
        "Megahorn": 102,
        "Dragon Breath": 70,
        "Baton Pass": 200,
        "Encore": 10,
        "Pursuit": 50,
        "Rapid Spin": 90,
        "Sweet Scent": 90,
        "Iron Tail": 115,
        "Metal Claw": 88,
        "Vital Throw": 10,
        "Morning Sun": 100,
        "Synthesis": 30,
        "Moonlight": 100,
        "Hidden Power": 70,
        "Cross Chop": 90,
        "Twister": 70,
        "Rain Dance": 30,
        "Sunny Day": 30,
        "Crunch": 120,
        "Mirror Coat": 120,
        "Psych Up": 10,
        "Extreme Speed": 90,
        "Ancient Power": 140,
        "Shadow Ball": 120,
        "Future Sight": 130,
        "Rock Smash": 80,
        "Whirlpool": 40,
        "Beat Up": 10,
        "Fake Out": 50,
        "Uproar": 130,
        "Stockpile": 90,
        "Spit Up": 10,
        "Swallow": 30,
        "Heat Wave": 116,
        "Hail": 30,
        "Torment": 10,
        "Flatter": 40,
        "Will O Wisp": 10,
        "Memento": 130,
        "Facade": 80,
        "Focus Punch": 160,
        "Smelling Salts": 80,
        "Follow Me": 30,
        "Nature Power": 20,
        "Charge": 60,
        "Taunt": 10,
        "Helping Hand": 30,
        "Trick": 20,
        "Role Play": 10,
        "Wish": 80,
        "Assist": 30,
        "Ingrain": 30,
        "Superpower": 190,
        "Magic Coat": 30,
        "Recycle": 40,
        "Revenge": 70,
        "Brick Break": 85,
        "Yawn": 10,
        "Knock Off": 75,
        "Endeavor": 80,
        "Eruption": 180,
        "Skill Swap": 10,
        "Imprison": 30,
        "Refresh": 30,
        "Grudge": 30,
        "Snatch": 30,
        "Secret Power": 90,
        "Dive": 90,
        "Arm Thrust": 55,
        "Camouflage": 30,
        "Tail Glow": 120,
        "Luster Purge": 110,
        "Mist Ball": 110,
        "Feather Dance": 70,
        "Teeter Dance": 30,
        "Blaze Kick": 87,
        "Mud Sport": 30,
        "Ice Ball": 50,
        "Needle Arm": 70,
        "Slack Off": 100,
        "Hyper Voice": 110,
        "Poison Fang": 60,
        "Crush Claw": 112,
        "Blast Burn": 145,
        "Hydro Cannon": 145,
        "Meteor Mash": 121,
        "Astonish": 40,
        "Weather Ball": 60,
        "Aromatherapy": 30,
        "Fake Tears": 70,
        "Air Cutter": 87,
        "Overheat": 187,
        "Odor Sleuth": 10,
        "Rock Tomb": 97,
        "Silver Wind": 130,
        "Metal Sound": 70,
        "Grass Whistle": 10,
        "Tickle": 70,
        "Cosmic Power": 90,
        "Water Spout": 180,
        "Signal Beam": 85,
        "Shadow Punch": 10,
        "Extrasensory": 90,
        "Sky Uppercut": 87,
        "Sand Tomb": 40,
        "Sheer Cold": 150,
        "Muddy Water": 137,
        "Bullet Seed": 85,
        "Aerial Ace": 10,
        "Icicle Spear": 85,
        "Iron Defense": 90,
        "Block": 10,
        "Howl": 60,
        "Dragon Claw": 80,
        "Frenzy Plant": 145,
        "Bulk Up": 90,
        "Bounce": 83,
        "Mud Shot": 93,
        "Poison Tail": 60,
        "Covet": 70,
        "Volt Tackle": 130,
        "Magical Leaf": 10,
        "Water Sport": 30,
        "Calm Mind": 90,
        "Leaf Blade": 100,
        "Dragon Dance": 90,
        "Rock Blast": 78,
        "Shock Wave": 10,
        "Water Pulse": 70,
        "Doom Desire": 150,
        "Psycho Boost": 196,
        "Roost": 80,
        "Gravity": 30,
        "Miracle Eye": 10,
        "Wake Up Slap": 80,
        "Hammer Arm": 130,
        "Gyro Ball": 10,
        "Healing Wish": 30,
        "Brine": 75,
        "Natural Gift": 10,
        "Feint": 40,
        "Pluck": 80,
        "Tailwind": 30,
        "Acupressure": 30,
        "Metal Burst": 120,
        "U-turn": 80,
        "Close Combat": 190,
        "Payback": 60,
        "Assurance": 70,
        "Embargo": 10,
        "Fling": 10,
        "Psycho Shift": 10,
        "Trump Card": 10,
        "Heal Block": 30,
        "Wring Out": 10,
        "Power Trick": 30,
        "Gastro Acid": 10,
        "Lucky Chant": 30,
        "Me First": 30,
        "Copycat": 30,
        "Power Swap": 10,
        "Guard Swap": 10,
        "Punishment": 10,
        "Last Resort": 150,
        "Worry Seed": 10,
        "Sucker Punch": 80,
        "Toxic Spikes": 30,
        "Heart Swap": 10,
        "Aqua Ring": 30,
        "Magnet Rise": 30,
        "Flare Blitz": 130,
        "Force Palm": 70,
        "Aura Sphere": 10,
        "Rock Polish": 90,
        "Poison Jab": 90,
        "Dark Pulse": 90,
        "Night Slash": 80,
        "Aqua Tail": 81,
        "Seed Bomb": 80,
        "Air Slash": 82,
        "X Scissor": 80,
        "Bug Buzz": 130,
        "Dragon Pulse": 85,
        "Dragon Rush": 85,
        "Power Gem": 80,
        "Drain Punch": 85,
        "Vacuum Wave": 50,
        "Focus Blast": 124,
        "Energy Ball": 130,
        "Brave Bird": 130,
        "Earth Power": 130,
        "Switcheroo": 10,
        "Giga Impact": 145,
        "Nasty Plot": 90,
        "Bullet Punch": 50,
        "Avalanche": 70,
        "Ice Shard": 50,
        "Shadow Claw": 80,
        "Thunder Fang": 72,
        "Ice Fang": 72,
        "Fire Fang": 72,
        "Shadow Sneak": 50,
        "Mud Bomb": 96,
        "Psycho Cut": 80,
        "Zen Headbutt": 82,
        "Mirror Shot": 96,
        "Flash Cannon": 120,
        "Rock Climb": 87,
        "Defog": 40,
        "Trick Room": 30,
        "Draco Meteor": 187,
        "Discharge": 110,
        "Lava Plume": 110,
        "Leaf Storm": 187,
        "Power Whip": 102,
        "Rock Wrecker": 145,
        "Cross Poison": 80,
        "Gunk Shot": 106,
        "Iron Head": 90,
        "Magnet Bomb": 10,
        "Stone Edge": 90,
        "Captivate": 90,
        "Stealth Rock": 30,
        "Grass Knot": 60,
        "Chatter": 75,
        "Judgment": 110,
        "Bug Bite": 70,
        "Charge Beam": 85,
        "Wood Hammer": 130,
        "Aqua Jet": 50,
        "Attack Order": 100,
        "Defend Order": 90,
        "Heal Order": 30,
        "Head Smash": 130,
        "Double Hit": 42,
        "Roar Of Time": 145,
        "Spacial Rend": 105,
        "Lunar Dance": 30,
        "Crush Grip": 80,
        "Magma Storm": 85,
        "Dark Void": 30,
        "Seed Flare": 172,
        "Ominous Wind": 130,
        "Shadow Force": 130,
        "Hone Claws": 90,
        "Wide Guard": 30,
        "Guard Split": 20,
        "Power Split": 10,
        "Wonder Room": 30,
        "Psyshock": 90,
        "Venoshock": 75,
        "Autotomize": 90,
        "Rage Powder": 30,
        "Telekinesis": 20,
        "Magic Room": 30,
        "Smack Down": 60,
        "Storm Throw": 70,
        "Flame Burst": 80,
        "Sludge Wave": 125,
        "Quiver Dance": 120,
        "Heavy Slam": 80,
        "Synchronoise": 40,
        "Electro Ball": 70,
        "Soak": 10,
        "Flame Charge": 90,
        "Coil": 120,
        "Low Sweep": 105,
        "Acid Spray": 110,
        "Foul Play": 105,
        "Simple Beam": 10,
        "Entrainment": 10,
        "After You": 10,
        "Round": 70,
        "Echoed Voice": 50,
        "Chip Away": 80,
        "Clear Smog": 10,
        "Stored Power": 150,
        "Quick Guard": 30,
        "Ally Switch": 40,
        "Scald": 100,
        "Shell Smash": 150,
        "Heal Pulse": 10,
        "Hex": 75,
        "Sky Drop": 70,
        "Shift Gear": 120,
        "Circle Throw": 64,
        "Incinerate": 90,
        "Quash": 10,
        "Acrobatics": 120,
        "Reflect Type": 10,
        "Retaliate": 80,
        "Final Gambit": 80,
        "Bestow": 10,
        "Inferno": 60,
        "Water Pledge": 90,
        "Fire Pledge": 90,
        "Grass Pledge": 90,
        "Volt Switch": 80,
        "Struggle Bug": 110,
        "Bulldoze": 120,
        "Frost Breath": 64,
        "Dragon Tail": 64,
        "Work Up": 90,
        "Electroweb": 113,
        "Wild Charge": 100,
        "Drill Run": 86,
        "Dual Chop": 46,
        "Heart Stamp": 70,
        "Horn Leech": 85,
        "Sacred Sword": 100,
        "Razor Shell": 112,
        "Heat Crash": 80,
        "Leaf Tornado": 99,
        "Steamroller": 75,
        "Cotton Guard": 120,
        "Night Daze": 121,
        "Psystrike": 110,
        "Tail Slap": 74,
        "Hurricane": 87,
        "Head Charge": 130,
        "Gear Grind": 53,
        "Searing Shot": 130,
        "Techno Blast": 130,
        "Relic Song": 105,
        "Secret Sword": 95,
        "Glaciate": 122,
        "Bolt Strike": 121,
        "Blue Flare": 121,
        "Fiery Dance": 120,
        "Freeze Shock": 136,
        "Ice Burn": 136,
        "Snarl": 113,
        "Icicle Crash": 87,
        "V-create": 271,
        "Fusion Flare": 110,
        "Fusion Bolt": 110,
        "Flying Press": 105,
        "Mat Block": 30,
        "Belch": 118,
        "Rototiller": 90,
        "Sticky Web": 30,
        "Fell Stinger": 60,
        "Phantom Force": 100,
        "Trick-Or-Treat": 40,
        "Noble Roar": 70,
        "Ion Deluge": 30,
        "Parabolic Charge": 95,
        "Forest's Curse": 10,
        "Petal Blizzard": 120,
        "Freeze Dry": 80,
        "Disarming Voice": 30,
        "Parting Shot": 70,
        "Topsy Turvy": 10,
        "Draining Kiss": 60,
        "Crafty Shield": 30,
        "Flower Shield": 70,
        "Grassy Terrain": 30,
        "Misty Terrain": 30,
        "Electrify": 10,
        "Play Rough": 121,
        "Fairy Wind": 40,
        "Moonblast": 135,
        "Boomburst": 170,
        "Fairy Lock": 30,
        "Kings Shield": 30,
        "Play Nice": 50,
        "Confide": 40,
        "Diamond Storm": 185,
        "Steam Eruption": 115,
        "Hyperspace Hole": 10,
        "Water Shuriken": 25,
        "Mystical Fire": 115,
        "Spiky Shield": 30,
        "Aromatic Mist": 70,
        "Eerie Impulse": 70,
        "Venom Drench": 120,
        "Powder": 10,
        "Geomancy": 210,
        "Magnetic Flux": 90,
        "Happy Hour": 30,
        "Electric Terrain": 30,
        "Dazzling Gleam": 100,
        "Celebrate": 30,
        "Hold Hands": 30,
        "Baby-Doll Eyes": 40,
        "Nuzzle": 30,
        "Hold Back": 50,
        "Infestation": 30,
        "Power-Up Punch": 80,
        "Oblivion Wing": 90,
        "Thousand Arrows": 120,
        "Thousand Waves": 120,
        "Lands Wrath": 110,
        "Light Of Ruin": 136,
        "Origin Pulse": 114,
        "Precipice Blades": 122,
        "Dragon Ascent": 190,
        "Hyperspace Fury": 40,
        "Breakneck Blitz  Physical": 0,
        "Breakneck Blitz  Special": 0,
        "All Out Pummeling  Physical": 0,
        "All Out Pummeling  Special": 0,
        "Supersonic Skystrike  Physical": 0,
        "Supersonic Skystrike  Special": 0,
        "Acid Downpour  Physical": 0,
        "Acid Downpour  Special": 0,
        "Tectonic Rage  Physical": 0,
        "Tectonic Rage  Special": 0,
        "Continental Crush  Physical": 0,
        "Continental Crush  Special": 0,
        "Savage Spin Out  Physical": 0,
        "Savage Spin Out  Special": 0,
        "Never Ending Nightmare  Physical": 0,
        "Never Ending Nightmare  Special": 0,
        "Corkscrew Crash  Physical": 0,
        "Corkscrew Crash  Special": 0,
        "Inferno Overdrive  Physical": 0,
        "Inferno Overdrive  Special": 0,
        "Hydro Vortex  Physical": 0,
        "Hydro Vortex  Special": 0,
        "Bloom Doom  Physical": 0,
        "Bloom Doom  Special": 0,
        "Gigavolt Havoc  Physical": 0,
        "Gigavolt Havoc  Special": 0,
        "Shattered Psyche  Physical": 0,
        "Shattered Psyche  Special": 0,
        "Subzero Slammer  Physical": 0,
        "Subzero Slammer  Special": 0,
        "Devastating Drake  Physical": 0,
        "Devastating Drake  Special": 0,
        "Black Hole Eclipse  Physical": 0,
        "Black Hole Eclipse  Special": 0,
        "Twinkle Tackle  Physical": 0,
        "Twinkle Tackle  Special": 0,
        "Catastropika": 0,
        "Shore Up": 100,
        "First Impression": 100,
        "Baneful Bunker": 60,
        "Spirit Shackle": 100,
        "Darkest Lariat": 95,
        "Sparkling Aria": 120,
        "Ice Hammer": 130,
        "Floral Healing": 10,
        "High Horsepower": 91,
        "Strength Sap": 40,
        "Solar Blade": 135,
        "Leafage": 40,
        "Spotlight": 10,
        "Toxic Thread": 50,
        "Laser Focus": 30,
        "Gear Up": 90,
        "Throat Chop": 90,
        "Pollen Puff": 100,
        "Anchor Shot": 90,
        "Psychic Terrain": 30,
        "Lunge": 120,
        "Fire Lash": 120,
        "Power Trip": 30,
        "Burn Up": 140,
        "Speed Swap": 10,
        "Smart Strike": 10,
        "Purify": 10,
        "Revelation Dance": 100,
        "Core Enforcer": 130,
        "Trop Kick": 110,
        "Instruct": 10,
        "Beak Blast": 110,
        "Clanging Scales": 170,
        "Dragon Hammer": 90,
        "Brutal Swing": 90,
        "Aurora Veil": 30,
        "Sinister Arrow Raid": 0,
        "Malicious Moonsault": 0,
        "Oceanic Operetta": 0,
        "Guardian Of Alola": 80,
        "Soul Stealing 7 Star Strike": 80,
        "Stoked Sparksurfer": 10,
        "Pulverizing Pancake": 0,
        "Extreme Evoboost": 330,
        "Genesis Supernova": 10,
        "Shell Trap": 180,
        "Fleur Cannon": 187,
        "Psychic Fangs": 95,
        "Stomping Tantrum": 85,
        "Shadow Bone": 125,
        "Accelerock": 50,
        "Liquidation": 125,
        "Prismatic Laser": 170,
        "Spectral Thief": 100,
        "Sunsteel Strike": 110,
        "Moongeist Beam": 110,
        "Tearful Look": 70,
        "Zing Zap": 90,
        "Natures Madness": 10,
        "Multi Attack": 130,
        "10,000,000 Volt Thunderbolt": 0,
        "Mind Blown": 180,
        "Plasma Fists": 100,
        "Photon Geyser": 100,
        "Light That Burns The Sky": 10,
        "Searing Sunraze Smash": 10,
        "Menacing Moonraze Maelstrom": 10,
        "Let's Snuggle Forever": 10,
        "Splintered Stormshards": 10,
        "Clangorous Soulblaze": 180,
        "Zippy Zap": 110,
        "Splishy Splash": 120,
        "Floaty Fall": 86,
        "Pika Papow": 0,
        "Bouncy Bubble": 60,
        "Buzzy Buzz": 60,
        "Sizzly Slide": 60,
        "Glitzy Glow": 76,
        "Baddy Bad": 76,
        "Sappy Seed": 90,
        "Freezy Frost": 90,
        "Sparkly Swirl": 102,
        "Veevee Volley": 0,
        "Double Iron Bash": 180,
        "Max Guard": 30,
        "Dynamax Cannon": 120,
        "Snipe Shot": 90,
        "Jaw Lock": 90,
        "Stuff Cheeks": 90,
        "No Retreat": 180,
        "Tar Shot": 40,
        "Magic Powder": 10,
        "Dragon Darts": 60,
        "Teatime": 30,
        "Octolock": 10,
        "Bolt Beak": 95,
        "Fishious Rend": 95,
        "Court Change": 30,
        "Max Flare": 20,
        "Max Flutterby": 20,
        "Max Lightning": 20,
        "Max Strike": 20,
        "Max Knuckle": 20,
        "Max Phantasm": 20,
        "Max Hailstorm": 20,
        "Max Ooze": 20,
        "Max Geyser": 20,
        "Max Airstream": 20,
        "Max Starfall": 20,
        "Max Wyrmwind": 20,
        "Max Mindstorm": 20,
        "Max Rockfall": 20,
        "Max Quake": 20,
        "Max Darkness": 20,
        "Max Overgrowth": 20,
        "Max Steelspike": 20,
        "Clangorous Soul": 180,
        "Body Press": 90,
        "Decorate": 130,
        "Drum Beating": 120,
        "Snap Trap": 45,
        "Pyro Ball": 118,
        "Behemoth Blade": 110,
        "Behemoth Bash": 110,
        "Aura Wheel": 150,
        "Breaking Swipe": 120,
        "Branch Poke": 40,
        "Overdrive": 110,
        "Apple Acid": 120,
        "Grav Apple": 120,
        "Spirit Break": 115,
        "Strange Steam": 96,
        "Life Dew": 30,
        "Obstruct": 30,
        "False Surrender": 20,
        "Meteor Assault": 160,
        "Eternabeam": 154,
        "Steel Beam": 143,
        "Expanding Force": 80,
        "Steel Roller": 130,
        "Scale Shot": 90,
        "Meteor Beam": 108,
        "Shell Side Arm": 90,
        "Misty Explosion": 120,
        "Grassy Glide": 55,
        "Rising Voltage": 70,
        "Terrain Pulse": 50,
        "Skitter Smack": 93,
        "Burning Jealousy": 90,
        "Lash Out": 75,
        "Poltergeist": 99,
        "Corrosive Gas": 20,
        "Coaching": 80,
        "Flip Turn": 60,
        "Triple Axel": 18,
        "Dual Wingbeat": 36,
        "Scorching Sands": 70,
        "Jungle Healing": 20,
        "Wicked Blow": 80,
        "Surging Strikes": 25,
        "Thunder Cage": 72,
        "Dragon Energy": 170,
        "Freezing Glare": 90,
        "Fiery Wrath": 110,
        "Thunderous Kick": 120,
        "Glacial Lance": 150,
        "Astral Barrage": 140,
        "Eerie Spell": 80,
        "Dire Claw": 90,
        "Psyshield Bash": 73,
        "Power Shift": 30,
        "Stone Axe": 69,
        "Springtide Storm": 110,
        "Mystical Power": 73,
        "Raging Fury": 150,
        "Wave Crash": 130,
        "Chloroblast": 153,
        "Mountain Gale": 95,
        "Victory Dance": 30,
        "Headlong Rush": 130,
        "Barb Barrage": 70,
        "Esper Wing": 90,
        "Bitter Malice": 85,
        "Shelter": 30,
        "Triple Arrows": 100,
        "Infernal Parade": 70,
        "Ceaseless Edge": 69,
        "Bleakwind Storm": 110,
        "Wildbolt Storm": 110,
        "Sandsear Storm": 110,
        "Lunar Blessing": 30,
        "Take Heart": 30,
        "Tera Blast": 90,
        "Silk Trap": 30,
        "Axe Kick": 128,
        "Last Respects": 60,
        "Lumina Crash": 90,
        "Order Up": 90,
        "Jet Punch": 70,
        "Spicy Extract": 10,
        "Spin Out": 110,
        "Population Bomb": 28,
        "Ice Spinner": 90,
        "Glaive Rush": 130,
        "Revival Blessing": 30,
        "Salt Cure": 50,
        "Triple Dive": 39,
        "Mortal Spin": 60,
        "Doodle": 10,
        "Fillet Away": 150,
        "Kowtow Cleave": 10,
        "Flower Trick": 10,
        "Torch Song": 90,
        "Aqua Step": 90,
        "Raging Bull": 100,
        "Make It Rain": 150,
        "Psyblade": 90,
        "Hydro Steam": 90,
        "Ruination": 11,
        "Collision Course": 110,
        "Electro Drift": 110,
        "Shed Tail": 90,
        "Chilly Reception": 30,
        "Tidy Up": 90,
        "Snowscape": 30,
        "Pounce": 60,
        "Trailblaze": 60,
        "Chilling Water": 60,
        "Hyper Drill": 110,
        "Twin Beam": 50,
        "Rage Fist": 60,
        "Armor Cannon": 130,
        "Bitter Blade": 100,
        "Double Shock": 130,
        "Gigaton Hammer": 170,
        "Comeuppance": 31,
        "Aqua Cutter": 80,
        "Blazing Torque": 90,
        "Wicked Torque": 90,
        "Noxious Torque": 110,
        "Combat Torque": 110,
        "Magical Torque": 110,
        "Blood Moon": 150,
        "Matcha Gotcha": 82,
        "Syrup Bomb": 61,
        "Ivy Cudgel": 110,
        "Shadow Rush": 65,
        "Shadow Blast": 90,
        "Shadow Blitz": 40,
        "Shadow Bolt": 85,
        "Shadow Break": 75,
        "Shadow Chill": 85,
        "Shadow End": 82,
        "Shadow Fire": 85,
        "Shadow Rave": 90,
        "Shadow Storm": 115,
        "Shadow Wave": 70,
        "Shadow Down": 30,
        "Shadow Half": 30,
        "Shadow Hold": 30,
        "Shadow Mist": 30,
        "Shadow Panic": 30,
        "Shadow Shed": 30,
        "Shadow Sky": 30
    }